// All UI text for both languages. Data content (targets, sectors, intel...) lives
// in the CSVs; this file is the chrome and page prose. Keys are dotted paths.
// Enum-like data values (category, type, basis, demand, signal) stay in English
// in the CSVs and are translated for display via the *Map entries below.

const en = {
  nav: {
    brand: 'Dira 2050', brandSub: 'Explained',
    vision: 'The Vision', pillars: 'Pillars', targets: 'Targets',
    timeline: 'Timeline', forYou: 'For You', data: 'Data',
    langLabel: 'Language', menu: 'Menu',
  },
  footer: {
    sub: 'Explained',
    tag: "A citizen's guide to the Tanzania Development Vision 2050.",
    vision: 'The Vision', pillars: 'Pillars & Drivers', targets: 'Targets',
    timeline: 'Timeline', data: 'Data & sources', about: 'About',
    fine: 'Targets are national aspirations for 2050, not current achievements. Source: United Republic of Tanzania, Tanzania Development Vision 2050 (National Planning Commission, 2025).',
  },
  common: {
    loading: 'Loading…', error: 'Could not load data.',
    sourceCite: 'Vision 2050, p.', pageAbbr: 'p.',
    documented: 'Documented', inferred: 'Inferred',
    documentedTip: 'Stated explicitly in the document',
    inferredTip: 'Analytical inference drawn from the document',
  },
  home: {
    eyebrow: 'Tanzania Development Vision 2050 · Dira 2050',
    titleA: 'The Tanzania', titleB: 'we want by 2050.',
    lead: 'A 25-year national plan to become an industrialised, knowledge-based, upper-middle-income country, with a one-trillion-dollar economy and a good life for every citizen. Here is what it says, in plain language.',
    ctaStart: 'Start with the Vision', ctaTargets: 'See the targets',
    goalLabel: 'The goal · by 2050',
    pillarsLabel: 'Three pillars',
    pillarsIntro: 'Everything in Dira 2050 stands on three pillars. Beneath them sits a foundation of good governance, peace and stability.',
    driversLabel: 'Five drivers',
    driversIntro: 'Five catalytic drivers power the whole Vision. They are the engine behind the pillars. Pick one to explore.',
    closingH2: 'This Vision belongs to everyone.',
    closingP: "Curious what it means for your own life: your job, your bills, your children's school? Read the plain-language guide.",
    closingCta: 'What it means for you',
  },
  vision: {
    label: 'The Vision', title: 'The Tanzania we want.',
    lead: 'By 2050, Tanzania aims to be an industrialised, knowledge-based, upper-middle-income country, with a one-trillion-dollar economy, an average income of US$7,000 per person, and a good life for all its people.',
    goalsLabel: 'Four goals', goalsIntro: 'Dira 2050 sets out four national goals for the next 25 years.',
    goals: [
      ['A strong economy', 'A diversified, resilient, inclusive and competitive upper-middle-income economy, worth one trillion dollars, with US$7,000 income per person.'],
      ['A good life for all', 'High quality of life and well-being for everyone: long, healthy lives, quality education and skills, clean water, decent housing and social protection.'],
      ['A cared-for environment', 'A nation that conserves and sustainably uses its natural resources, maintains environmental integrity, and is resilient to climate change.'],
      ['A digital society', "A digitally empowered society that embraces innovation and drives the country's productivity and competitiveness."],
    ],
    howLabel: 'How it works',
    howBody: 'The Vision rests on a foundation of good governance, peace and stability. On that base stand three pillars: a strong economy, capable people and a healthy environment. Powering them are five drivers: logistics, energy, science & technology, research & development, and digital transformation. And it is delivered through prioritised transformative sectors like agriculture, tourism, manufacturing and mining.',
    btnFramework: 'Explore the framework', btnTargets: 'See the targets',
  },
  framework: {
    label: 'The framework', title: 'How Dira 2050 is built.',
    intro: 'A foundation of good governance holds up three pillars. Five drivers power them, delivering the Vision goals.',
    foundationLabel: 'Foundation',
    foundationIntro: 'Governance, peace, security and stability: the bedrock the whole Vision rests on.',
    pillarsLabel: 'Three pillars', driversLabel: 'Five drivers',
  },
  pillar: {
    crumb: 'Pillars', word: 'Pillar', of: 'of', aims: 'What it aims for · by 2050',
  },
  driver: {
    crumb: 'Drivers', word: 'Driver', of: 'of',
    targets: 'Targets · by 2050', aspirations: 'Aspirations',
    aspirationsIntro: 'What Tanzania wants this driver to look like by 2050.',
  },
  targets: {
    label: 'Targets',
    title: (n) => `${n} targets. One deadline: 2050.`,
    intro: (m) => `Where Tanzania is now, and where Dira 2050 aims to be. ${m} of these carry a measurable 2050 figure, and the bars show how big each leap really is. Every figure links back to a page in the source document.`,
    filters: { all: 'All', economy: 'Economy', people: 'People', environment: 'Environment', drivers: 'Drivers' },
    count: (n) => `${n} target${n === 1 ? '' : 's'}`,
    now: 'Now', goal: '2050', of: 'of',
    tagEliminate: 'Eliminate', tagReduce: 'Reduce', tagIncrease: 'Increase', tagGrow: 'Grow',
  },
  timeline: {
    label: 'Timeline', title: 'From 2000 to 2050.',
    intro: "Dira 2050 builds on decades of progress and runs on a 25-year plan. Here are the markers that matter: where Tanzania started, where it is now, and where it's headed.",
  },
  forYou: {
    label: 'For you', title: 'What does Dira 2050 mean for your life?',
    lead: 'Big national targets are really promises about everyday things: your income, your lights, your water, your children’s school. Here’s what the Vision is reaching for, in plain terms. Tap any underlined word for a quick explanation.',
    sections: [
      { h2: 'More money in your pocket', parts: [
        'The plan aims to lift ', { label: 'average income per person', def: "The country's total output divided by its people; a rough measure of average income per person." },
        ' to about US$7,000 a year, more than five times what it was in 2023. It wants at least half of all Tanzanians in decent, formal jobs, and ',
        { label: 'extreme poverty', def: 'Living on so little that basic needs like food and shelter cannot be met.' }, ' gone for good.' ] },
      { h2: 'Power you can count on', parts: [
        'Today the average person uses only about 170 ', { label: 'kWh', def: 'Kilowatt-hour: a unit of electricity; using more per person usually signals a more developed economy.' },
        ' of electricity a year. By 2050 the goal is at least 3,000, enough for reliable light, appliances and small businesses, with fewer outages as transmission losses are cut below 10%.' ] },
      { h2: 'Clean water and better health', parts: [
        'The Vision promises safe, clean water for everyone, ', { label: 'health coverage for all', def: 'Everyone can get the health care they need without financial hardship.' },
        ', and a longer life, an average of 75 years. It aims to end deaths of mothers and babies during childbirth (today ',
        { label: 'maternal deaths', def: 'The number of women who die from pregnancy or childbirth, per 100,000 live births.' }, ' stand at 104 per 100,000 births, down from 750 in 2000).' ] },
      { h2: 'School and skills for your children', parts: [
        'Every child should get quality education from early childhood upward, with a strong push on ',
        { label: 'STEM', def: 'Science, Technology, Engineering and Mathematics; skills seen as key to a modern economy.' },
        ' skills. At least one in four young people should reach higher education with skills the job market actually needs.' ] },
      { h2: 'Getting online', parts: [
        'The plan wants at least 70% of citizens to have ', { label: 'digital skills', def: 'Being able to use computers, phones and the internet confidently for everyday tasks.' },
        ' and more than 80% of government services available online, so paying, applying and registering means fewer queues and less travel.' ] },
      { h2: 'A fair shot for everyone', parts: [
        'Growth is meant to be inclusive. The Vision singles out women, youth and persons with disabilities, aims to cut the gender gap by at least 85%, and wants Tanzania to reach ',
        { label: 'upper-middle-income status', def: 'A World Bank income group; Tanzania aims to move up into it by earning more per person.' }, ' without leaving anyone behind.' ] },
    ],
  },
  data: {
    label: 'Data & sources', title: 'Open data. Every figure sourced.',
    lead: 'This site is built entirely from the official Vision 2050 document. Every dataset is downloadable as a plain CSV, and every figure carries the page it came from. Use them freely.',
    downloadLabel: 'Download', methodologyLabel: 'Methodology',
    methodologyBody: 'Figures were extracted from the full 76-page PDF. Where the document gives a baseline and a 2050 target, both are shown. Blank cells mean the document gives no value, never a guess. Some per-sector indicators and phase details remain to be deepened; these are logged in the data notes.',
    btnPdf: 'Source PDF', btnNotes: 'Data notes', rows: 'rows',
    files: {
      'pillars.csv': 'The three pillars', 'enablers.csv': 'The five drivers',
      'foundation.csv': 'Governance foundation', 'targets.csv': 'National, pillar, driver & sector targets',
      'sectors.csv': 'Transformative sectors', 'sector_kpis.csv': 'Sector baseline figures',
      'sector_criteria.csv': 'Sector selection criteria', 'aspirations.csv': 'Driver aspirations',
      'milestones.csv': 'Timeline milestones', 'glossary.csv': 'Plain-language definitions',
      'sources.csv': 'Document section map',
    },
  },
  about: {
    label: 'About', title: 'Dira 2050, made clear.',
    lead: "A plain-language, citizen's guide to the Tanzania Development Vision 2050, so every Tanzanian can understand where the country is headed.",
    noteLabel: 'Please note',
    noteBody: "These are goals, not achievements. Every target on this site is a national aspiration for 2050 as set out in the Vision document. They describe what Tanzania is reaching for, not what has already been accomplished. Where a target has a starting point, we show today's figure next to the 2050 goal so the distance is clear.",
    sourceLabel: 'Source',
    sourceBody: 'United Republic of Tanzania. (2025). Tanzania Development Vision 2050 (Dira 2050). Dodoma: National Planning Commission. All content on this site is drawn from that document.',
    independentLabel: 'Independent',
    independentBody: 'This is an independent explainer to aid public understanding. It is not an official government publication.',
    founderLabel: 'About the founder',
    founderP1: 'This project is part of a broader effort to build an independent Information Visualization Institute, dedicated to making complex public information easier to understand through clear, accessible, evidence-based visual communication. The long-term vision is to turn government strategies, policies, research, statistics, budgets and development reports into interactive experiences that help citizens, researchers, policymakers, educators and development partners understand the issues shaping society.',
    founderP2: "The initiative was founded by Gerald Tesha, an Information Systems and Network Engineer (St. Joseph College of Engineering and Technology) with a specialisation in Information Visualization from the NYU Tandon School of Engineering. Based in Dodoma, Tanzania, Gerald has more than nine years' experience in data, monitoring and evaluation, information management and visualization across health and international-development programs in Sub-Saharan Africa.",
    founderP3: 'Collaborators, researchers, designers, software engineers, institutions and organisations interested in advancing this work are warmly welcome to get in touch.',
  },
  si: {
    deepDive: 'Deep dive', eyebrow: 'Opportunities & Strategic Intelligence',
    h2: "Don't just read the plan. Find your place in it.",
    lead: 'Every national strategy quietly signals where investment, jobs, skills and growth are heading. This layer extracts that intelligence from Dira 2050 and turns it into decisions you can act on.',
    legendDoc: 'stated in the document.', legendInf: 'our analysis of what it implies.',
    forLabel: 'Intelligence for…',
    opportunities: 'Opportunities', actions: 'Actions to consider', skills: 'Skills to build',
    sectors: 'Sectors to watch', engage: 'Institutions to engage',
    tailored: (a) => `tailored analysis for ${a}.`,
    outlookLabel: 'Sector outlook',
    outlookIntro: "Where the document points the most attention. Bars show relative strategic emphasis (1–5), read from the plan's targets, drivers and named sectors.",
    mapLabel: 'Opportunity map',
    skillsLabel: 'Skills in demand',
    skillsIntro: 'The competencies the plan will pull on: what to study, teach or reskill into.',
    demand: (d) => `${d} demand`,
    briefingLabel: 'Strategic briefing',
    briefingIntro: "The systemic picture: what the plan prioritises, what it depends on, where it's weak, and the levers most likely to move it.",
  },
  notFound: { code: '404', title: 'Page not found.', body: "The page you're looking for doesn't exist.", home: 'Return home' },
  // Display maps for enum values kept in English in the CSVs
  maps: {
    demand: { High: 'High', Medium: 'Medium' },
    signal: { Rising: 'Rising', Emerging: 'Emerging' },
    category: { Priority: 'Priority', Dependency: 'Dependency', 'Capability gap': 'Capability gap', Bottleneck: 'Bottleneck', 'Leverage point': 'Leverage point', Risk: 'Risk' },
    categoryPlural: { Priority: 'Priorities', Dependency: 'Dependencies', 'Capability gap': 'Capability gaps', Bottleneck: 'Bottlenecks', 'Leverage point': 'Leverage points', Risk: 'Risks' },
    oppType: { Investment: 'Investment', 'Local manufacturing': 'Local manufacturing', Export: 'Export', Startup: 'Startup', Innovation: 'Innovation', Research: 'Research', PPP: 'PPP', Employment: 'Employment', 'Capacity-building': 'Capacity-building', 'Technology adoption': 'Technology adoption', Funding: 'Funding' },
  },
}

const sw = {
  nav: {
    brand: 'Dira 2050', brandSub: 'Kwa Ufafanuzi',
    vision: 'Dira', pillars: 'Nguzo', targets: 'Shabaha',
    timeline: 'Ratiba', forYou: 'Kwako', data: 'Takwimu',
    langLabel: 'Lugha', menu: 'Menyu',
  },
  footer: {
    sub: 'Kwa Ufafanuzi',
    tag: 'Mwongozo wa mwananchi kuhusu Dira ya Taifa ya Maendeleo 2050.',
    vision: 'Dira', pillars: 'Nguzo na Vichocheo', targets: 'Shabaha',
    timeline: 'Ratiba', data: 'Takwimu na vyanzo', about: 'Kuhusu',
    fine: 'Shabaha ni malengo ya kitaifa ya mwaka 2050, si mafanikio ya sasa. Chanzo: Jamhuri ya Muungano wa Tanzania, Dira ya Taifa ya Maendeleo 2050 (Tume ya Mipango, 2025).',
  },
  common: {
    loading: 'Inapakia…', error: 'Imeshindwa kupakia takwimu.',
    sourceCite: 'Dira 2050, uk.', pageAbbr: 'uk.',
    documented: 'Imeandikwa', inferred: 'Uchambuzi',
    documentedTip: 'Imeelezwa wazi katika waraka',
    inferredTip: 'Uchambuzi uliotokana na waraka',
  },
  home: {
    eyebrow: 'Dira ya Taifa ya Maendeleo 2050 · Dira 2050',
    titleA: 'Tanzania', titleB: 'tunayoitaka ifikapo 2050.',
    lead: 'Mpango wa kitaifa wa miaka 25 wa kuifanya Tanzania kuwa nchi ya viwanda, yenye uchumi wa maarifa na kipato cha kati ngazi ya juu, ikiwa na uchumi wa dola trilioni moja na maisha bora kwa kila mwananchi. Hapa ni yaliyomo, kwa lugha rahisi.',
    ctaStart: 'Anza na Dira', ctaTargets: 'Ona shabaha',
    goalLabel: 'Lengo · ifikapo 2050',
    pillarsLabel: 'Nguzo tatu',
    pillarsIntro: 'Kila kitu katika Dira 2050 kinasimama juu ya nguzo tatu. Chini yake kuna msingi wa utawala bora, amani na utulivu.',
    driversLabel: 'Vichocheo vitano',
    driversIntro: 'Vichocheo vitano vinasukuma Dira nzima. Ndivyo injini iliyo nyuma ya nguzo. Chagua kimoja kuvinjari.',
    closingH2: 'Dira hii ni ya kila mmoja wetu.',
    closingP: 'Unataka kujua inamaanisha nini kwa maisha yako: kazi yako, bili zako, shule ya watoto wako? Soma mwongozo wa lugha rahisi.',
    closingCta: 'Inamaanisha nini kwako',
  },
  vision: {
    label: 'Dira', title: 'Tanzania tunayoitaka.',
    lead: 'Ifikapo 2050, Tanzania inalenga kuwa nchi ya viwanda, yenye uchumi wa maarifa na kipato cha kati ngazi ya juu, ikiwa na uchumi wa dola trilioni moja, wastani wa kipato cha dola 7,000 kwa mtu, na maisha bora kwa watu wote.',
    goalsLabel: 'Malengo manne', goalsIntro: 'Dira 2050 imeweka malengo manne ya kitaifa kwa miaka 25 ijayo.',
    goals: [
      ['Uchumi imara', 'Uchumi wa kipato cha kati ngazi ya juu, ulio mseto, himilivu, jumuishi na shindani, wenye thamani ya dola trilioni moja, na kipato cha dola 7,000 kwa mtu.'],
      ['Maisha bora kwa wote', 'Maisha bora na ustawi kwa kila mtu: maisha marefu na yenye afya, elimu na ujuzi bora, maji safi, makazi bora na hifadhi ya jamii.'],
      ['Mazingira yaliyohifadhiwa', 'Taifa linalohifadhi na kutumia rasilimali za asili kwa uendelevu, linalodumisha usalama wa mazingira, na linalostahimili mabadiliko ya tabianchi.'],
      ['Jamii ya kidijitali', 'Jamii yenye umahiri wa kidijitali inayokumbatia ubunifu na kuongeza tija na ushindani wa nchi.'],
    ],
    howLabel: 'Inavyofanya kazi',
    howBody: 'Dira imejengwa juu ya msingi wa utawala bora, amani na utulivu. Juu ya msingi huo zimesimama nguzo tatu: uchumi imara, watu wenye uwezo, na mazingira yenye afya. Zinasukumwa na vichocheo vitano: usafirishaji, nishati, sayansi na teknolojia, utafiti na maendeleo, na mageuzi ya kidijitali. Na inatekelezwa kupitia sekta za mageuzi zilizopewa kipaumbele kama kilimo, utalii, viwanda na madini.',
    btnFramework: 'Vinjari muundo', btnTargets: 'Ona shabaha',
  },
  framework: {
    label: 'Muundo', title: 'Jinsi Dira 2050 ilivyojengwa.',
    intro: 'Msingi wa utawala bora unashikilia nguzo tatu. Vichocheo vitano vinazisukuma, vikitekeleza malengo ya Dira.',
    foundationLabel: 'Msingi',
    foundationIntro: 'Utawala bora, amani, usalama na utulivu: msingi ambao Dira nzima inaukalia.',
    pillarsLabel: 'Nguzo tatu', driversLabel: 'Vichocheo vitano',
  },
  pillar: {
    crumb: 'Nguzo', word: 'Nguzo', of: 'kati ya', aims: 'Inalenga nini · ifikapo 2050',
  },
  driver: {
    crumb: 'Vichocheo', word: 'Kichocheo', of: 'kati ya',
    targets: 'Shabaha · ifikapo 2050', aspirations: 'Matarajio',
    aspirationsIntro: 'Jinsi Tanzania inavyotaka kichocheo hiki kionekane ifikapo 2050.',
  },
  targets: {
    label: 'Shabaha',
    title: (n) => `Shabaha ${n}. Muda mmoja: 2050.`,
    intro: (m) => `Tanzania ilipo sasa, na Dira 2050 inakolenga. ${m} kati ya hizi zina takwimu ya 2050 inayopimika, na mistari inaonyesha ukubwa wa hatua inayohitajika. Kila takwimu inarejea ukurasa katika waraka wa chanzo.`,
    filters: { all: 'Zote', economy: 'Uchumi', people: 'Watu', environment: 'Mazingira', drivers: 'Vichocheo' },
    count: (n) => `Shabaha ${n}`,
    now: 'Sasa', goal: '2050', of: 'kati ya',
    tagEliminate: 'Kutokomeza', tagReduce: 'Kupunguza', tagIncrease: 'Kuongeza', tagGrow: 'Kukua',
  },
  timeline: {
    label: 'Ratiba', title: 'Kuanzia 2000 hadi 2050.',
    intro: 'Dira 2050 inajengwa juu ya miongo ya maendeleo na inaendeshwa kwa mpango wa miaka 25. Hizi ni alama muhimu: Tanzania ilipoanzia, ilipo sasa, na inakoelekea.',
  },
  forYou: {
    label: 'Kwako', title: 'Dira 2050 inamaanisha nini kwa maisha yako?',
    lead: 'Shabaha kubwa za kitaifa kwa kweli ni ahadi kuhusu mambo ya kila siku: kipato chako, umeme wako, maji yako, shule ya watoto wako. Haya ndiyo Dira inayolenga, kwa lugha rahisi. Gusa neno lolote lililopigiwa mstari kwa maelezo mafupi.',
    sections: [
      { h2: 'Pesa zaidi mfukoni mwako', parts: [
        'Mpango unalenga kuinua ', { label: 'wastani wa kipato cha mtu', def: 'Pato lote la nchi likigawanywa kwa idadi ya watu; kipimo cha jumla cha kipato cha mtu mmoja.' },
        ' hadi takriban dola 7,000 kwa mwaka, zaidi ya mara tano ya kiwango cha 2023. Unataka angalau nusu ya Watanzania wawe na ajira zenye staha katika sekta rasmi, na ',
        { label: 'umaskini uliokithiri', def: 'Kuishi kwa kipato kidogo mno kiasi cha kushindwa kumudu mahitaji ya msingi kama chakula na makazi.' }, ' utokomezwe kabisa.' ] },
      { h2: 'Umeme wa uhakika', parts: [
        'Leo mtu wa wastani anatumia takriban 170 ', { label: 'kWh', def: 'Kilowati-saa: kipimo cha umeme; matumizi makubwa kwa mtu mara nyingi yanaashiria uchumi ulioendelea zaidi.' },
        ' za umeme kwa mwaka. Ifikapo 2050 lengo ni angalau 3,000, ya kutosha kwa mwanga wa uhakika, vifaa na biashara ndogo, huku upotevu wa umeme ukishuka chini ya 10%.' ] },
      { h2: 'Maji safi na afya bora', parts: [
        'Dira inaahidi maji safi na salama kwa kila mtu, ', { label: 'huduma za afya kwa wote', def: 'Kila mtu anaweza kupata huduma za afya anazohitaji bila kuingia matatizo ya kifedha.' },
        ', na maisha marefu zaidi, wastani wa miaka 75. Inalenga kutokomeza vifo vya akina mama na watoto wakati wa kujifungua (leo ',
        { label: 'vifo vya uzazi', def: 'Idadi ya wanawake wanaofariki kutokana na ujauzito au kujifungua, kwa kila vizazi hai 100,000.' }, ' viko 104 kwa kila vizazi 100,000, kutoka 750 mwaka 2000).' ] },
      { h2: 'Shule na ujuzi kwa watoto wako', parts: [
        'Kila mtoto apate elimu bora kuanzia utotoni, kwa msukumo mkubwa kwenye ujuzi wa ',
        { label: 'STEM', def: 'Sayansi, Teknolojia, Uhandisi na Hisabati; ujuzi unaoonekana muhimu kwa uchumi wa kisasa.' },
        '. Angalau mtoto mmoja kati ya wanne afike elimu ya juu akiwa na ujuzi unaohitajika sokoni.' ] },
      { h2: 'Kuingia mtandaoni', parts: [
        'Mpango unataka angalau 70% ya wananchi wawe na ', { label: 'ujuzi wa kidijitali', def: 'Kuweza kutumia kompyuta, simu na intaneti kwa ujasiri katika shughuli za kila siku.' },
        ' na zaidi ya 80% ya huduma za serikali zipatikane mtandaoni, ili kulipa, kuomba na kujisajili kumaanishe foleni chache na safari chache.' ] },
      { h2: 'Nafasi sawa kwa kila mtu', parts: [
        'Ukuaji unakusudiwa kuwa jumuishi. Dira inawataja wanawake, vijana na watu wenye ulemavu, inalenga kupunguza pengo la kijinsia kwa angalau 85%, na inataka Tanzania ifikie ',
        { label: 'kipato cha kati ngazi ya juu', def: 'Kundi la kipato la Benki ya Dunia; Tanzania inalenga kupanda hadi humo kwa kuongeza kipato kwa mtu.' }, ' bila kumwacha mtu nyuma.' ] },
    ],
  },
  data: {
    label: 'Takwimu na vyanzo', title: 'Takwimu huru. Kila namba ina chanzo.',
    lead: 'Tovuti hii imejengwa kikamilifu kutoka waraka rasmi wa Dira 2050. Kila seti ya takwimu inapakuliwa kama faili la CSV, na kila namba ina ukurasa ilikotoka. Zitumie bila vikwazo.',
    downloadLabel: 'Pakua', methodologyLabel: 'Mbinu',
    methodologyBody: 'Namba zimetolewa kutoka waraka kamili wa kurasa 76. Pale waraka unapotoa msingi na lengo la 2050, vyote vinaonyeshwa. Visanduku tupu vinamaanisha waraka haukutoa thamani, si kubuni. Baadhi ya viashiria vya sekta na maelezo ya awamu bado yanahitaji kuchambuliwa zaidi; haya yameandikwa katika maelezo ya takwimu.',
    btnPdf: 'Waraka wa PDF', btnNotes: 'Maelezo ya takwimu', rows: 'safu',
    files: {
      'pillars.csv': 'Nguzo tatu', 'enablers.csv': 'Vichocheo vitano',
      'foundation.csv': 'Msingi wa utawala', 'targets.csv': 'Shabaha za taifa, nguzo, vichocheo na sekta',
      'sectors.csv': 'Sekta za mageuzi', 'sector_kpis.csv': 'Takwimu za msingi za sekta',
      'sector_criteria.csv': 'Vigezo vya kuchagua sekta', 'aspirations.csv': 'Matarajio ya vichocheo',
      'milestones.csv': 'Alama za ratiba', 'glossary.csv': 'Maelezo ya lugha rahisi',
      'sources.csv': 'Ramani ya sehemu za waraka',
    },
  },
  about: {
    label: 'Kuhusu', title: 'Dira 2050, kwa uwazi.',
    lead: 'Mwongozo wa lugha rahisi kwa mwananchi kuhusu Dira ya Taifa ya Maendeleo 2050, ili kila Mtanzania aelewe nchi inakoelekea.',
    noteLabel: 'Tafadhali fahamu',
    noteBody: 'Haya ni malengo, si mafanikio. Kila shabaha katika tovuti hii ni lengo la kitaifa la mwaka 2050 kama lilivyowekwa katika waraka wa Dira. Yanaeleza Tanzania inayolenga, si yaliyokwisha fikiwa. Pale shabaha ina mahali pa kuanzia, tunaonyesha takwimu ya leo pembeni na lengo la 2050 ili umbali uwe wazi.',
    sourceLabel: 'Chanzo',
    sourceBody: 'Jamhuri ya Muungano wa Tanzania. (2025). Dira ya Taifa ya Maendeleo 2050 (Dira 2050). Dodoma: Tume ya Mipango. Maudhui yote ya tovuti hii yametokana na waraka huo.',
    independentLabel: 'Huru',
    independentBody: 'Huu ni mwongozo huru wa kusaidia uelewa wa umma. Si chapisho rasmi la serikali.',
    founderLabel: 'Kuhusu mwanzilishi',
    founderP1: 'Mradi huu ni sehemu ya jitihada pana za kuanzisha Taasisi huru ya Uonyeshaji wa Taarifa (Information Visualization Institute), inayolenga kurahisisha uelewa wa taarifa tata za umma kupitia mawasiliano ya kuona yaliyo wazi, yanayofikika na yenye msingi wa ushahidi. Dira ya muda mrefu ni kugeuza mikakati ya serikali, sera, tafiti, takwimu, bajeti na ripoti za maendeleo kuwa uzoefu shirikishi unaosaidia wananchi, watafiti, watunga sera, waelimishaji na washirika wa maendeleo kuelewa masuala yanayounda jamii.',
    founderP2: 'Jitihada hii ilianzishwa na Gerald Tesha, Mhandisi wa Mifumo ya Taarifa na Mitandao (St. Joseph College of Engineering and Technology) mwenye utaalamu wa Uonyeshaji wa Taarifa kutoka NYU Tandon School of Engineering. Akiwa Dodoma, Tanzania, Gerald ana uzoefu wa zaidi ya miaka tisa katika takwimu, ufuatiliaji na tathmini, usimamizi wa taarifa na uonyeshaji katika programu za afya na maendeleo ya kimataifa Kusini mwa Jangwa la Sahara.',
    founderP3: 'Washirika, watafiti, wabunifu, wahandisi wa programu, taasisi na mashirika wanaopenda kuendeleza kazi hii wanakaribishwa kuwasiliana.',
  },
  si: {
    deepDive: 'Uchambuzi wa kina', eyebrow: 'Fursa na Ujasusi wa Kimkakati',
    h2: 'Usisome tu mpango. Tafuta nafasi yako ndani yake.',
    lead: 'Kila mkakati wa kitaifa unaashiria kimya kimya uwekezaji, ajira, ujuzi na ukuaji unakoelekea. Safu hii inatoa ujasusi huo kutoka Dira 2050 na kuugeuza kuwa maamuzi unayoweza kuyachukua.',
    legendDoc: 'imeelezwa katika waraka.', legendInf: 'uchambuzi wetu wa maana yake.',
    forLabel: 'Ujasusi kwa…',
    opportunities: 'Fursa', actions: 'Hatua za kuzingatia', skills: 'Ujuzi wa kujenga',
    sectors: 'Sekta za kufuatilia', engage: 'Taasisi za kushirikiana nazo',
    tailored: (a) => `uchambuzi maalum kwa ${a}.`,
    outlookLabel: 'Mtazamo wa sekta',
    outlookIntro: 'Pale waraka unapoelekeza uangalifu mkubwa. Mistari inaonyesha msisitizo wa kimkakati (1–5), uliosomwa kutoka shabaha, vichocheo na sekta zilizotajwa.',
    mapLabel: 'Ramani ya fursa',
    skillsLabel: 'Ujuzi unaohitajika',
    skillsIntro: 'Ujuzi ambao mpango utautegemea: cha kusoma, kufundisha au kujifunza upya.',
    demand: (d) => `mahitaji ${d}`,
    briefingLabel: 'Muhtasari wa kimkakati',
    briefingIntro: 'Picha ya jumla: mpango unapaweka kipaumbele, unategemea nini, uko dhaifu wapi, na nyenzo zenye uwezekano mkubwa wa kuusukuma.',
  },
  notFound: { code: '404', title: 'Ukurasa haukupatikana.', body: 'Ukurasa unaoutafuta haupo.', home: 'Rudi mwanzo' },
  maps: {
    demand: { High: 'makubwa', Medium: 'ya wastani' },
    signal: { Rising: 'Inapanda', Emerging: 'Inachipuka' },
    category: { Priority: 'Kipaumbele', Dependency: 'Utegemezi', 'Capability gap': 'Pengo la uwezo', Bottleneck: 'Kizuizi', 'Leverage point': 'Nyenzo ya kusukuma', Risk: 'Hatari' },
    categoryPlural: { Priority: 'Vipaumbele', Dependency: 'Tegemezi', 'Capability gap': 'Mapengo ya uwezo', Bottleneck: 'Vizuizi', 'Leverage point': 'Nyenzo za kusukuma', Risk: 'Hatari' },
    oppType: { Investment: 'Uwekezaji', 'Local manufacturing': 'Uzalishaji wa ndani', Export: 'Mauzo ya nje', Startup: 'Biashara mpya', Innovation: 'Ubunifu', Research: 'Utafiti', PPP: 'Ubia (PPP)', Employment: 'Ajira', 'Capacity-building': 'Kujenga uwezo', 'Technology adoption': 'Matumizi ya teknolojia', Funding: 'Ufadhili' },
  },
}

export default { en, sw }
