// All UI text for both languages. Data content (targets, sectors, intel...) lives
// in the CSVs; this file is the chrome and page prose. Keys are dotted paths.
// Enum-like data values (category, type, basis, demand, signal) stay in English
// in the CSVs and are translated for display via the *Map entries below.

const en = {
  nav: {
    brand: 'Dira 2050', brandSub: 'Explained',
    vision: 'The Vision', pillars: 'Pillars', targets: 'Targets',
    timeline: 'Timeline', forYou: 'For You', data: 'Data', quiz: 'Knowledge check',
    langLabel: 'Language', menu: 'Menu', hub: 'All plans',
  },
  quiz: {
    label: 'Knowledge check',
    title: 'How well do you know Dira 2050?',
    lead: 'A short, playful quiz across the whole Vision: its goals, pillars, drivers and how it will be delivered. Multiple choice, ordering and matching.',
    back: 'Back to overview',
  },
  hub: {
    eyebrow: 'The United Republic of Tanzania · National Planning Commission',
    title: 'Tanzania’s road to 2050, explained',
    lead: 'One place to understand the national plan: the vision it aims for, the 25-year path, the first five-year plan, and how it all gets delivered and measured.',
    live: 'Live', soon: 'Coming soon', open: 'Open', companionLabel: 'Companion',
    companionNote: 'How the Vision is communicated to citizens and stakeholders.',
    cards: {
      dira: { title: 'Vision 2050', tag: 'The national vision: where the country is heading.' },
      ltpp: { title: 'Long Term Perspective Plan', tag: 'The 25-year path, 2026 to 2050.' },
      fydp: { title: 'Fourth Five-Year Development Plan', tag: 'The first five years, 2026/27 to 2030/31.' },
      framework: { title: 'National Delivery Framework', tag: 'How progress is delivered and tracked.' },
      comms: { title: 'Communication Strategy', tag: 'How the Vision reaches people.' },
    },
  },
  coming: {
    badge: 'Coming soon',
    body: 'This section is being prepared. It will explain the document as clearly as the Dira 2050 site, in English.',
    back: 'Back to all plans',
  },
  footer: {
    sub: 'Explained',
    tag: "A citizen's guide to the Tanzania Development Vision 2050.",
    vision: 'The Vision', pillars: 'Pillars & Drivers', targets: 'Targets',
    timeline: 'Timeline', data: 'Data & sources', about: 'About',
    fine: 'Targets are national aspirations for 2050, not current achievements. Source: United Republic of Tanzania, Tanzania Development Vision 2050 (National Planning Commission, 2025).',
  },
  common: {
    loading: 'Loading…', error: 'Could not load data.',
    sourceCite: 'Vision 2050, p.', pageAbbr: 'p.',
    documented: 'Documented', inferred: 'Inferred',
    documentedTip: 'Stated explicitly in the document',
    inferredTip: 'Analytical inference drawn from the document',
  },
  home: {
    eyebrow: 'Tanzania Development Vision 2050 · Dira 2050',
    titleA: 'The Tanzania', titleB: 'we want by 2050.',
    lead: 'A 25-year national plan to become an industrialised, knowledge-based, upper-middle-income country, with a one-trillion-dollar economy and a good life for every citizen.',
    leadSub: 'Here is what it says, in plain language.',
    facts: ['Industrialised', 'Knowledge-based', 'Upper-middle-income', 'Digitally empowered'],
    ctaStart: 'Start with the Vision', ctaTargets: 'See the targets',
    goalLabel: 'The goal · by 2050',
    pillarsLabel: 'Three pillars',
    pillarsIntro: 'Everything in Dira 2050 stands on three pillars. Beneath them sits a foundation of good governance, peace and stability.',
    driversLabel: 'Five drivers',
    driversIntro: 'Five catalytic drivers power the whole Vision. They are the engine behind the pillars. Pick one to explore.',
    closingH2: 'This Vision belongs to everyone.',
    closingP: "Curious what it means for your own life: your job, your bills, your children's school? Read the plain-language guide.",
    closingCta: 'What it means for you',
  },
  vision: {
    label: 'The Vision', title: 'The Tanzania we want.',
    lead: 'By 2050, Tanzania aims to be an industrialised, knowledge-based, upper-middle-income country, with a one-trillion-dollar economy, an average income of US$7,000 per person, and a good life for all its people.',
    goalsLabel: 'Four goals', goalsIntro: 'Dira 2050 sets out four national goals for the next 25 years.',
    goals: [
      ['A strong economy', 'A diversified, resilient, inclusive and competitive upper-middle-income economy, worth one trillion dollars, with US$7,000 income per person.'],
      ['A good life for all', 'High quality of life and well-being for everyone: long, healthy lives, quality education and skills, clean water, decent housing and social protection.'],
      ['A cared-for environment', 'A nation that conserves and sustainably uses its natural resources, maintains environmental integrity, and is resilient to climate change.'],
      ['A digital society', "A digitally empowered society that embraces innovation and drives the country's productivity and competitiveness."],
    ],
    howLabel: 'How it works',
    howBody: 'The Vision rests on a foundation of good governance, peace and stability. On that base stand three pillars: a strong economy, capable people and a healthy environment. Powering them are five drivers: logistics, energy, science & technology, research & development, and digital transformation. And it is delivered through prioritised transformative sectors like agriculture, tourism, manufacturing and mining.',
    btnFramework: 'Explore the framework', btnTargets: 'See the targets',
    principlesLabel: 'Guiding principles',
    principlesIntro: 'Five principles form the basis for realising the Vision.',
    principles: [
      ['Democracy, rights and freedoms', 'Rights and protections for every person, upheld through the constitution, judicial independence, political pluralism and the rule of law, with inclusive participation for women, youth and people with disabilities.'],
      ['Dignity', 'Every person is respected, valued and cared for, and enjoys the highest standard of privacy and protection.'],
      ['Peace and unity', 'Everyone upholds peace, unity and solidarity as the cornerstone of development, safeguarding the Union, respecting one another and working toward shared national goals.'],
      ['Natural wealth and resources', "Full sovereignty over the nation's natural wealth and resources, as invaluable assets for the benefit of citizens and future generations."],
      ['Culture and national ethos', 'A nation that preserves, promotes and safeguards its positive cultural heritage and national ethos, reinforcing national identity and unity for generations to come.'],
    ],
    deliveryLabel: 'How it will be delivered',
    deliveryIntro: 'Dira 2050 sets out how the Vision moves from paper to results.',
    delivery: [
      ['Strategic prioritisation', 'With limited resources, the Vision concentrates on a few transformative sectors, chosen for their potential to create jobs, grow exports, link to other sectors, raise revenue and add value.'],
      ['Phased implementation', 'Delivery runs through a 25-year Long-Term Perspective Plan, which frames the five-year plans (starting with FYDP IV) and the annual plans beneath them.'],
      ['Engaging every actor', 'Success depends on collaboration: government leadership, private-sector innovation, civil society and citizen participation, working through public-private partnerships.'],
      ['Coordination and oversight', 'The National Planning Commission, with the Zanzibar Planning Commission, coordinates delivery and aligns sector policies and plans, so even party manifestos anchor in the Vision.'],
      ['Evidence and accountability', 'A robust national data system and evidence-driven monitoring, evaluation and learning guide decisions, backed by performance indicators and incentives for accountability.'],
    ],
  },
  framework: {
    label: 'The framework', title: 'How Dira 2050 is built.',
    intro: 'A foundation of good governance holds up three pillars. Five drivers power them, delivering the Vision goals.',
    foundationLabel: 'Foundation',
    foundationIntro: 'Governance, peace, security and stability: the bedrock the whole Vision rests on.',
    pillarsLabel: 'Three pillars', driversLabel: 'Five drivers',
  },
  pillar: {
    crumb: 'Pillars', word: 'Pillar', of: 'of', aims: 'What it aims for · by 2050',
  },
  driver: {
    crumb: 'Drivers', word: 'Driver', of: 'of',
    targets: 'Targets · by 2050', aspirations: 'Aspirations',
    aspirationsIntro: 'What Tanzania wants this driver to look like by 2050.',
  },
  targets: {
    label: 'Targets',
    title: (n) => `${n} targets. One deadline: 2050.`,
    intro: (m) => `Where Tanzania is now, and where Dira 2050 aims to be. ${m} of these carry a measurable 2050 figure, and the bars show how big each leap really is. Every figure links back to a page in the source document.`,
    filters: { all: 'All', economy: 'Economy', people: 'People', environment: 'Environment', drivers: 'Drivers' },
    count: (n) => `${n} target${n === 1 ? '' : 's'}`,
    now: 'Now', goal: '2050', of: 'of',
    tagEliminate: 'Eliminate', tagReduce: 'Reduce', tagIncrease: 'Increase', tagGrow: 'Grow',
  },
  timeline: {
    label: 'Timeline', title: 'From 2000 to 2050.',
    intro: "Dira 2050 builds on decades of progress and runs on a 25-year plan. Here are the markers that matter: where Tanzania started, where it is now, and where it's headed.",
  },
  forYou: {
    label: 'For you', title: 'What does Dira 2050 mean for your life?',
    lead: 'Big national targets are really promises about everyday things: your income, your lights, your water, your children’s school. Here’s what the Vision is reaching for, in plain terms. Tap any underlined word for a quick explanation.',
    sections: [
      { h2: 'More money in your pocket', parts: [
        'The plan aims to lift ', { label: 'average income per person', def: "The country's total output divided by its people; a rough measure of average income per person." },
        ' to about US$7,000 a year, more than five times what it was in 2023. It wants at least half of all Tanzanians in decent, formal jobs, and ',
        { label: 'extreme poverty', def: 'Living on so little that basic needs like food and shelter cannot be met.' }, ' gone for good.' ] },
      { h2: 'Power you can count on', parts: [
        'Today the average person uses only about 170 ', { label: 'kWh', def: 'Kilowatt-hour: a unit of electricity; using more per person usually signals a more developed economy.' },
        ' of electricity a year. By 2050 the goal is at least 3,000, enough for reliable light, appliances and small businesses, with fewer outages as transmission losses are cut below 10%.' ] },
      { h2: 'Clean water and better health', parts: [
        'The Vision promises safe, clean water for everyone, ', { label: 'health coverage for all', def: 'Everyone can get the health care they need without financial hardship.' },
        ', and a longer life, an average of 75 years. It aims to end deaths of mothers and babies during childbirth (today ',
        { label: 'maternal deaths', def: 'The number of women who die from pregnancy or childbirth, per 100,000 live births.' }, ' stand at 104 per 100,000 births, down from 750 in 2000).' ] },
      { h2: 'School and skills for your children', parts: [
        'Every child should get quality education from early childhood upward, with a strong push on ',
        { label: 'STEM', def: 'Science, Technology, Engineering and Mathematics; skills seen as key to a modern economy.' },
        ' skills. At least one in four young people should reach higher education with skills the job market actually needs.' ] },
      { h2: 'Getting online', parts: [
        'The plan wants at least 70% of citizens to have ', { label: 'digital skills', def: 'Being able to use computers, phones and the internet confidently for everyday tasks.' },
        ' and more than 80% of government services available online, so paying, applying and registering means fewer queues and less travel.' ] },
      { h2: 'A fair shot for everyone', parts: [
        'Growth is meant to be inclusive. The Vision singles out women, youth and persons with disabilities, aims to cut the gender gap by at least 85%, and wants Tanzania to reach ',
        { label: 'upper-middle-income status', def: 'A World Bank income group; Tanzania aims to move up into it by earning more per person.' }, ' without leaving anyone behind.' ] },
    ],
  },
  data: {
    label: 'Data & sources', title: 'Open data. Every figure sourced.',
    lead: 'This site is built entirely from the official Vision 2050 document. Every dataset is downloadable as a plain CSV, and every figure carries the page it came from. Use them freely.',
    downloadLabel: 'Download', methodologyLabel: 'Methodology',
    methodologyBody: 'Figures were extracted from the full 76-page PDF. Where the document gives a baseline and a 2050 target, both are shown. Blank cells mean the document gives no value, never a guess. Some per-sector indicators and phase details remain to be deepened; these are logged in the data notes.',
    btnPdf: 'Source PDF', btnNotes: 'Data notes', rows: 'rows',
    files: {
      'pillars.csv': 'The three pillars', 'enablers.csv': 'The five drivers',
      'foundation.csv': 'Governance foundation', 'targets.csv': 'National, pillar, driver & sector targets',
      'sectors.csv': 'Transformative sectors', 'sector_kpis.csv': 'Sector baseline figures',
      'sector_criteria.csv': 'Sector selection criteria', 'aspirations.csv': 'Driver aspirations',
      'milestones.csv': 'Timeline milestones', 'glossary.csv': 'Plain-language definitions',
      'sources.csv': 'Document section map',
    },
  },
  about: {
    label: 'About', title: 'Dira 2050, made clear.',
    lead: "A plain-language, citizen's guide to the Tanzania Development Vision 2050, so every Tanzanian can understand where the country is headed.",
    noteLabel: 'Please note',
    noteBody: "These are goals, not achievements. Every target on this site is a national aspiration for 2050 as set out in the Vision document. They describe what Tanzania is reaching for, not what has already been accomplished. Where a target has a starting point, we show today's figure next to the 2050 goal so the distance is clear.",
    sourceLabel: 'Source',
    sourceBody: 'United Republic of Tanzania. (2025). Tanzania Development Vision 2050 (Dira 2050). Dodoma: National Planning Commission. All content on this site is drawn from that document.',
    independentLabel: 'Independent',
    independentBody: 'This is an independent explainer to aid public understanding. It is not an official government publication.',
    founderLabel: 'About the founder',
    founderP1: 'This project is part of a broader effort to build an independent Information Visualization Institute, dedicated to making complex public information easier to understand through clear, accessible, evidence-based visual communication. The long-term vision is to turn government strategies, policies, research, statistics, budgets and development reports into interactive experiences that help citizens, researchers, policymakers, educators and development partners understand the issues shaping society.',
    founderP2: "The initiative was founded by Gerald Tesha, an Information Systems and Network Engineer (St. Joseph College of Engineering and Technology) with a specialisation in Information Visualization from the NYU Tandon School of Engineering. Based in Dodoma, Tanzania, Gerald has more than nine years' experience in data, monitoring and evaluation, information management and visualization across health and international-development programs in Sub-Saharan Africa.",
    founderP3: 'Collaborators, researchers, designers, software engineers, institutions and organisations interested in advancing this work are warmly welcome to get in touch.',
  },
  si: {
    deepDive: 'Deep dive', eyebrow: 'Opportunities & Strategic Intelligence',
    h2: "Don't just read the plan. Find your place in it.",
    lead: 'Every national strategy quietly signals where investment, jobs, skills and growth are heading. This layer extracts that intelligence from Dira 2050 and turns it into decisions you can act on.',
    legendDoc: 'stated in the document.', legendInf: 'our analysis of what it implies.',
    forLabel: 'Intelligence for…',
    opportunities: 'Opportunities', actions: 'Actions to consider', skills: 'Skills to build',
    sectors: 'Sectors to watch', engage: 'Institutions to engage',
    tailored: (a) => `tailored analysis for ${a}.`,
    outlookLabel: 'Sector outlook',
    outlookIntro: "Where the document points the most attention. Bars show relative strategic emphasis (1–5), read from the plan's targets, drivers and named sectors.",
    mapLabel: 'Opportunity map',
    skillsLabel: 'Skills in demand',
    skillsIntro: 'The competencies the plan will pull on: what to study, teach or reskill into.',
    demand: (d) => `${d} demand`,
    briefingLabel: 'Strategic briefing',
    briefingIntro: "The systemic picture: what the plan prioritises, what it depends on, where it's weak, and the levers most likely to move it.",
    oppIntro: 'What the Vision opens up, tailored to who you are: the opportunities, the actions to consider, the skills to build, the sectors to watch and the institutions to engage.',
    mapIntro: 'Concrete opportunities the Vision creates, filterable by type. Each is tied back to the document.',
    back: 'Back to For You',
    exploreLabel: 'Explore the intelligence',
    explore: [
      ['opportunities', 'Opportunities', 'What the Vision opens up for you, tailored by who you are.'],
      ['sector-outlook', 'Sector outlook', 'Where the plan points the most attention, sector by sector.'],
      ['opportunity-map', 'Opportunity map', 'Concrete opportunities, filterable by type, each tied to the document.'],
      ['skills', 'Skills in demand', 'The competencies the plan will pull on.'],
      ['briefing', 'Strategic briefing', 'Priorities, dependencies, weak spots and the levers that move them.'],
    ],
  },
  notFound: { code: '404', title: 'Page not found.', body: "The page you're looking for doesn't exist.", home: 'Return home' },
  pro: {
    nav: 'PRO',
    home: {
      eyebrow: 'National Information Intelligence',
      title: 'Vision 2050, as a living intelligence platform.',
      lead: 'Beyond the document: an interactive, evidence-based exploration of what Tanzania aims to achieve, why it matters, and how you can take part.',
      cta: 'Enter the Executive Story', ctaExplore: 'Explore the Vision',
      keyNumbers: 'The 2050 ambition, in three numbers',
      roadmapLabel: 'What PRO opens up', roadmapLead: 'A suite of intelligence modules, built in phases on this foundation.',
      libraryLabel: 'Built on a storytelling toolkit', libraryLead: 'Reusable, bilingual, accessible components that power every PRO story.',
      comingSoon: 'Coming soon',
    },
    story: {
      scrollCue: 'Scroll to begin',
      journeyEyebrow: 'The journey',
      journeyTitle: 'Six decades of progress, one 25-year plan.',
      journeyLead: 'Dira 2050 builds on where Tanzania has been and sets a clear direction for where it is going.',
      transformEyebrow: 'The transformation',
      transformTitle: 'How far the leap really is.',
      transformLead: 'Not slogans, but measurable change from today to 2050.',
      leapGrowth: 'growth by 2050',
      leapCut: 'reduction by 2050',
      numbersEyebrow: 'The ambition, in numbers',
      pillarsEyebrow: 'The framework',
      pillarsTitle: 'Three pillars, one foundation.',
      pillarsLead: 'Everything stands on good governance, and rises through a strong economy, capable people and a healthy environment.',
      ambitionsEyebrow: 'National goals',
      ambitionsTitle: 'What success looks like by 2050.',
      ctaEyebrow: 'Go deeper',
      ctaTitle: 'This is only the beginning.',
      ctaLead: 'Explore the Vision in depth, or dive into the intelligence modules as they open.',
      ctaVision: 'Explore the framework', ctaTargets: 'See every target', ctaForYou: 'What it means for you',
    },
    subnav: { story: 'Story', explore: 'Explore', graph: 'Graph', opps: 'Opportunities', skills: 'Skills', audiences: 'Audiences', regions: 'Regions', sectors: 'Sectors', charts: 'Charts', evidence: 'Evidence', ask: 'Ask', progress: 'Progress' },
    progress: {
      title: 'Progress Monitoring',
      lead: 'The architecture to track delivery against every 2050 target. Live indicators plug in here as official data becomes available.',
      note: 'Live monitoring is not yet connected. This view is built to accept official indicator data through a standard adapter, so no redesign is needed when it arrives.',
      baseline: 'Baseline', goal: '2050 goal', current: 'Current', awaiting: 'Awaiting data',
      statusNodata: 'Monitoring pending', statusOn: 'On track', statusBehind: 'Behind', statusMet: 'Met',
    },
    error: {
      badge: 'Something went wrong',
      title: 'This view could not be displayed',
      body: 'An unexpected error stopped this section from loading. The rest of the platform is unaffected. You can try again, or return to the overview.',
      retry: 'Try again', home: 'Back to overview',
    },
    ask: {
      title: 'Ask the Vision',
      lead: 'A private assistant that answers from the Vision, entirely in your browser. No data leaves your device.',
      placeholder: 'Ask a question about Dira 2050…', ask: 'Ask',
      suggestions: ['What are the 2050 targets for energy?', 'Opportunities in tourism', 'Which skills should students build?', 'What is the Human Capital Index?', 'Explain the economy pillar'],
      answerLead: 'Here’s what Dira 2050 says, drawn from the data:',
      noAnswer: 'I couldn’t find anything on that in the Vision. Try different words, or explore the sections.',
      privacy: 'Runs entirely in your browser · no external calls',
      types: { pillar: 'Pillar', driver: 'Driver', sector: 'Sector', target: 'Target', foundation: 'Foundation', glossary: 'Definition', opportunity: 'Opportunity', skill: 'Skill', audience: 'Audience', region: 'Region', strategic: 'Insight' },
    },
    evidence: {
      title: 'Evidence & Method',
      lead: 'Every figure and claim on this platform traces back to the source. Here is how, and where.',
      methodTitle: 'Documented vs Inferred',
      methodBody: 'Facts stated in the Vision document are marked Documented. Analytical insights we draw from it (opportunities, skills, regional and sector framing) are marked Inferred, so you always know which is which.',
      statDatasets: 'Open datasets', statFigures: 'Targets tracked', statSections: 'Document sections',
      sourcesTitle: 'Document sections', sourcesLead: 'The Tanzania Development Vision 2050, mapped by section and page.',
      colSection: 'Section', colPages: 'Pages',
      pdf: 'Source PDF', downloads: 'Download the data',
    },
    charts: {
      title: 'Data Stories', lead: 'Charts that answer a question, not decorate the page.',
      treemapTitle: 'What makes up the economy today?', treemapNote: 'By share of GDP. “Other & services” is the remainder.',
      sankeyTitle: 'Which drivers power which sectors?', sankeyNote: 'Enabling links from the five drivers to the transformative sectors.',
      smTitle: 'Every target’s leap, at a glance', smNote: 'Today (grey) versus the 2050 goal (green), each scaled to its own maximum.',
      other: 'Other & services', now: 'Now', goal: '2050',
    },
    sector: {
      title: 'Sector Intelligence',
      lead: 'A portal for each transformative sector: where it is today, where it is heading by 2050, and the opportunities within.',
      badge: 'Sector', ambition: 'The 2050 ambition', kpis: 'Key figures', opportunities: 'Opportunities', connections: 'Other sectors',
      why: 'Why it matters', take: 'What it will take', momentum: 'Momentum', pageAbbr: 'p.',
    },
    regions: {
      title: 'Regional Intelligence',
      lead: 'How the Vision plays out across Tanzania: the priorities, industries, resources and opportunities of each zone.',
      disclaimer: 'Regional profiles are analytical, illustrative summaries. The Vision sets national direction, not region-by-region detail.',
      selectLabel: 'Select a zone', mapNote: 'Schematic map, not to scale',
      priorities: 'Development priorities', industries: 'Industries', resources: 'Resources', opportunities: 'Opportunities',
    },
    audience: {
      title: 'Audience Intelligence',
      lead: 'Tailored guidance for who you are: the opportunities, actions, skills and institutions that matter most to you.',
      choose: 'Choose your role', backAll: 'All audiences', ctaSkills: 'Explore skills', ctaOpps: 'Explore opportunities',
    },
    skills: {
      title: 'Skills Intelligence',
      lead: 'The capabilities the Vision will pull on: what to study, teach or reskill into, with learning paths and career outlooks.',
      allCats: 'All areas', allDemand: 'All demand',
      whereLabel: 'In the strategy', learningLabel: 'Learning path', certsLabel: 'Certifications',
      programsLabel: 'University programs', outlookLabel: 'Career outlook', demandLabel: 'Demand',
      count: (n) => `${n} skill${n === 1 ? '' : 's'}`,
      cats: { Digital: 'Digital', Policy: 'Policy', Engineering: 'Engineering', Agriculture: 'Agriculture', Operations: 'Operations', Environment: 'Environment', Research: 'Research', Health: 'Health' },
    },
    opps: {
      title: 'Opportunity Intelligence',
      lead: 'What the Vision opens up: structured business, investment, employment and innovation opportunities, each tied to the document.',
      allTypes: 'All types', allTimes: 'All timelines',
      stakeholders: 'Who', impact: 'Potential impact', evidence: 'Evidence', priority: 'Priority',
      timelines: { 'Near-term': 'Near-term', 'Medium-term': 'Medium-term', 'Long-term': 'Long-term' },
      count: (n) => `${n} opportunit${n === 1 ? 'y' : 'ies'}`,
    },
    graph: {
      title: 'The Knowledge Graph',
      lead: 'How the Vision connects: from the goal, through the pillars and drivers, to the sectors that deliver it. Click any node to explore.',
      visionNode: 'Dira 2050',
      legend: { vision: 'Vision', pillar: 'Pillars', driver: 'Drivers', sector: 'Sectors' },
      listLabel: 'All nodes',
      structureTitle: 'The structure',
      structureLead: 'The Vision read top to bottom: the goal, the three pillars, the drivers that power them, and the sectors where it happens.',
      connectionsTitle: 'The connections',
      connectionsLead: 'The same Vision as a network. Hover or tap any node to trace how the pillars, drivers and sectors interconnect.',
      tiers: { vision: 'The vision', pillars: 'Pillars · the goals', drivers: 'Drivers · the enablers', sectors: 'Sectors · where it happens' },
    },
    storyt: {
      why: 'Why it matters', aims: 'What it aims for by 2050', aspirations: 'Aspirations',
      timeline: 'The journey to 2050', connections: 'Explore more', fullPage: 'View the full page',
    },
    stories: {
      why: {
        economy: 'A bigger, fairer economy funds everything else: schools, hospitals, roads and jobs. Without growth that reaches everyone, the other goals stay out of reach.',
        people: 'People are the point of development. Healthier, better-educated and more secure citizens are both the goal of the Vision and the workforce that delivers it.',
        environment: "Tanzania's land, water and wildlife are national wealth and a livelihood for millions. Protecting them, and adapting to a changing climate, keeps growth from undermining itself.",
        logistics: 'When moving goods is slow and costly, everything is more expensive. Cheaper, faster logistics unlock trade, industry and regional leadership.',
        energy: 'Almost nothing in the Vision works without power. Reliable, affordable energy is the precondition for factories, digital services and modern life.',
        'science-tech': 'Technology is how a smaller economy leapfrogs. Applied science raises what a farmer, a clinic or a factory can produce.',
        rnd: 'Research turns problems into products and evidence into policy. Under-funded today, it is the engine of long-term competitiveness.',
        digital: 'Going digital cuts cost and distance: fewer queues, wider markets, and services that reach rural areas. It threads through every other ambition.',
      },
    },
    explore: {
      title: 'Explore the Vision',
      lead: 'Search and navigate every part of Dira 2050: goals, targets, pillars, drivers, sectors and more, all connected.',
      searchPlaceholder: 'Search the Vision…',
      related: 'Connected to', open: 'Open',
      noResults: 'Nothing matches your search.',
      count: (n) => `${n} result${n === 1 ? '' : 's'}`,
      facet: { all: 'All', goal: 'Goals', target: 'Targets', pillar: 'Pillars', driver: 'Drivers', sector: 'Sectors', foundation: 'Foundation', principle: 'Principles', theme: 'Themes' },
      badge: { goal: 'Goal', target: 'Target', pillar: 'Pillar', driver: 'Driver', sector: 'Sector', foundation: 'Foundation', principle: 'Principle', theme: 'Theme' },
      principles: [
        ['Human-centred development', 'Growth that improves the life of every citizen, leaving no one behind.'],
        ['Sovereignty over resources', "Using the nation's natural wealth for the benefit of current and future generations."],
        ['Culture and national ethos', 'Preserving heritage, identity and unity as a foundation for progress.'],
        ['Good governance', 'Constitutionalism, the rule of law and accountability as the bedrock of the Vision.'],
      ],
      themes: [
        ['Inclusion', 'Women, youth and persons with disabilities are central to every goal.'],
        ['Youth & demographics', 'A young population as the engine of transformation.'],
        ['Digital transformation', 'Technology woven through the economy and public services.'],
        ['Climate resilience', 'Adapting to climate change across every sector.'],
        ['Jobs & skills', 'Decent work, and the capabilities to fill it.'],
      ],
    },
    modules: [
      ['Executive Story', 'A cinematic, scroll-driven introduction to the Vision.'],
      ['Vision Explorer', 'Explore by goals, targets, pillars, drivers and sectors, all interconnected.'],
      ['Knowledge Graph', 'See how goals, sectors, skills, regions and institutions connect.'],
      ['Opportunity Intelligence', 'Structured business, investment and innovation opportunities per section.'],
      ['Skills Intelligence', 'Future skills, learning paths and career outlooks.'],
      ['Ask the Vision', 'A private assistant that answers questions from the document.'],
    ],
    demo: {
      quote: 'By 2050, we will build an upper-middle-income country of more than 118 million people, with a one-trillion-dollar economy.',
      quoteCite: 'Tanzania Development Vision 2050',
      compareLabel: 'Income per person (USD)',
      calloutTitle: 'Everything here is evidence-based',
      calloutBody: 'Every figure and claim traces back to the Vision document, and analytical insights are clearly marked apart from documented facts.',
      expTitle: 'How is the Vision structured?',
      expBody: 'A foundation of good governance holds up three pillars (economy, people, environment). Five drivers power them, delivered through prioritised transformative sectors.',
      tl: [
        ['2000', 'Starting point', 'Per capita income US$453; extreme poverty 36%.'],
        ['2025', 'Dira 2050 adopted', 'A 25-year national direction is set.'],
        ['2050', 'The Tanzania we want', 'A one-trillion-dollar, upper-middle-income economy.'],
      ],
    },
  },
  // Display maps for enum values kept in English in the CSVs
  maps: {
    demand: { High: 'High', Medium: 'Medium' },
    signal: { Rising: 'Rising', Emerging: 'Emerging' },
    category: { Priority: 'Priority', Dependency: 'Dependency', 'Capability gap': 'Capability gap', Bottleneck: 'Bottleneck', 'Leverage point': 'Leverage point', Risk: 'Risk' },
    categoryPlural: { Priority: 'Priorities', Dependency: 'Dependencies', 'Capability gap': 'Capability gaps', Bottleneck: 'Bottlenecks', 'Leverage point': 'Leverage points', Risk: 'Risks' },
    oppType: { Investment: 'Investment', 'Local manufacturing': 'Local manufacturing', Export: 'Export', Startup: 'Startup', Innovation: 'Innovation', Research: 'Research', PPP: 'PPP', Employment: 'Employment', 'Capacity-building': 'Capacity-building', 'Technology adoption': 'Technology adoption', Funding: 'Funding' },
  },
}

const sw = {
  nav: {
    brand: 'Dira 2050', brandSub: 'Kwa Ufafanuzi',
    vision: 'Dira', pillars: 'Nguzo', targets: 'Shabaha',
    timeline: 'Ratiba', forYou: 'Kwako', data: 'Takwimu', quiz: 'Jaribio la maarifa',
    langLabel: 'Lugha', menu: 'Menyu', hub: 'Mipango yote',
  },
  quiz: {
    label: 'Jaribio la maarifa',
    title: 'Unaifahamu vipi Dira 2050?',
    lead: 'Jaribio fupi na la kufurahisha kuhusu Dira nzima: malengo, nguzo, vichocheo na jinsi itakavyotekelezwa. Chagua jibu, panga, na oanisha.',
    back: 'Rudi kwenye muhtasari',
  },
  hub: {
    eyebrow: 'Jamhuri ya Muungano wa Tanzania · Tume ya Taifa ya Mipango',
    title: 'Safari ya Tanzania hadi 2050, kwa ufafanuzi',
    lead: 'Mahali pamoja pa kuelewa mpango wa taifa: dira inayolengwa, njia ya miaka 25, mpango wa kwanza wa miaka mitano, na jinsi yote yanavyotekelezwa na kufuatiliwa.',
    live: 'Hai', soon: 'Inakuja hivi karibuni', open: 'Fungua', companionLabel: 'Nyongeza',
    companionNote: 'Jinsi Dira inavyowasilishwa kwa wananchi na wadau.',
    cards: {
      dira: { title: 'Dira 2050', tag: 'Dira ya taifa: nchi inakoelekea.' },
      ltpp: { title: 'Mpango wa Mtazamo wa Muda Mrefu', tag: 'Njia ya miaka 25, 2026 hadi 2050.' },
      fydp: { title: 'Mpango wa Nne wa Maendeleo wa Miaka Mitano', tag: 'Miaka mitano ya kwanza, 2026/27 hadi 2030/31.' },
      framework: { title: 'Mfumo wa Taifa wa Utekelezaji', tag: 'Jinsi maendeleo yanavyotekelezwa na kufuatiliwa.' },
      comms: { title: 'Mkakati wa Mawasiliano', tag: 'Jinsi Dira inavyowafikia watu.' },
    },
  },
  coming: {
    badge: 'Inakuja hivi karibuni',
    body: 'Sehemu hii inaandaliwa. Itaeleza waraka kwa uwazi kama tovuti ya Dira 2050, kwa Kiingereza.',
    back: 'Rudi kwa mipango yote',
  },
  footer: {
    sub: 'Kwa Ufafanuzi',
    tag: 'Mwongozo wa mwananchi kuhusu Dira ya Taifa ya Maendeleo 2050.',
    vision: 'Dira', pillars: 'Nguzo na Vichocheo', targets: 'Shabaha',
    timeline: 'Ratiba', data: 'Takwimu na vyanzo', about: 'Kuhusu',
    fine: 'Shabaha ni malengo ya kitaifa ya mwaka 2050, si mafanikio ya sasa. Chanzo: Jamhuri ya Muungano wa Tanzania, Dira ya Taifa ya Maendeleo 2050 (Tume ya Mipango, 2025).',
  },
  common: {
    loading: 'Inapakia…', error: 'Imeshindwa kupakia takwimu.',
    sourceCite: 'Dira 2050, uk.', pageAbbr: 'uk.',
    documented: 'Imeandikwa', inferred: 'Uchambuzi',
    documentedTip: 'Imeelezwa wazi katika waraka',
    inferredTip: 'Uchambuzi uliotokana na waraka',
  },
  home: {
    eyebrow: 'Dira ya Taifa ya Maendeleo 2050 · Dira 2050',
    titleA: 'Tanzania', titleB: 'tunayoitaka ifikapo 2050.',
    lead: 'Mpango wa kitaifa wa miaka 25 wa kuifanya Tanzania kuwa nchi ya viwanda, yenye uchumi wa maarifa na kipato cha kati ngazi ya juu, ikiwa na uchumi wa dola trilioni moja na maisha bora kwa kila mwananchi.',
    leadSub: 'Hapa ni yaliyomo, kwa lugha rahisi.',
    facts: ['Nchi ya viwanda', 'Uchumi wa maarifa', 'Kipato cha kati ngazi ya juu', 'Jamii ya kidijitali'],
    ctaStart: 'Anza na Dira', ctaTargets: 'Ona shabaha',
    goalLabel: 'Lengo · ifikapo 2050',
    pillarsLabel: 'Nguzo tatu',
    pillarsIntro: 'Kila kitu katika Dira 2050 kinasimama juu ya nguzo tatu. Chini yake kuna msingi wa utawala bora, amani na utulivu.',
    driversLabel: 'Vichocheo vitano',
    driversIntro: 'Vichocheo vitano vinasukuma Dira nzima. Ndivyo injini iliyo nyuma ya nguzo. Chagua kimoja kuvinjari.',
    closingH2: 'Dira hii ni ya kila mmoja wetu.',
    closingP: 'Unataka kujua inamaanisha nini kwa maisha yako: kazi yako, bili zako, shule ya watoto wako? Soma mwongozo wa lugha rahisi.',
    closingCta: 'Inamaanisha nini kwako',
  },
  vision: {
    label: 'Dira', title: 'Tanzania tunayoitaka.',
    lead: 'Ifikapo 2050, Tanzania inalenga kuwa nchi ya viwanda, yenye uchumi wa maarifa na kipato cha kati ngazi ya juu, ikiwa na uchumi wa dola trilioni moja, wastani wa kipato cha dola 7,000 kwa mtu, na maisha bora kwa watu wote.',
    goalsLabel: 'Malengo manne', goalsIntro: 'Dira 2050 imeweka malengo manne ya kitaifa kwa miaka 25 ijayo.',
    goals: [
      ['Uchumi imara', 'Uchumi wa kipato cha kati ngazi ya juu, ulio mseto, himilivu, jumuishi na shindani, wenye thamani ya dola trilioni moja, na kipato cha dola 7,000 kwa mtu.'],
      ['Maisha bora kwa wote', 'Maisha bora na ustawi kwa kila mtu: maisha marefu na yenye afya, elimu na ujuzi bora, maji safi, makazi bora na hifadhi ya jamii.'],
      ['Mazingira yaliyohifadhiwa', 'Taifa linalohifadhi na kutumia rasilimali za asili kwa uendelevu, linalodumisha usalama wa mazingira, na linalostahimili mabadiliko ya tabianchi.'],
      ['Jamii ya kidijitali', 'Jamii yenye umahiri wa kidijitali inayokumbatia ubunifu na kuongeza tija na ushindani wa nchi.'],
    ],
    howLabel: 'Inavyofanya kazi',
    howBody: 'Dira imejengwa juu ya msingi wa utawala bora, amani na utulivu. Juu ya msingi huo zimesimama nguzo tatu: uchumi imara, watu wenye uwezo, na mazingira yenye afya. Zinasukumwa na vichocheo vitano: usafirishaji, nishati, sayansi na teknolojia, utafiti na maendeleo, na mageuzi ya kidijitali. Na inatekelezwa kupitia sekta za mageuzi zilizopewa kipaumbele kama kilimo, utalii, viwanda na madini.',
    btnFramework: 'Vinjari muundo', btnTargets: 'Ona shabaha',
    principlesLabel: 'Misingi ya Dira',
    principlesIntro: 'Misingi mitano ndiyo msingi wa kufikia Dira.',
    principles: [
      ['Demokrasia, haki na uhuru', 'Kila mtu anafurahia uhuru na haki zote za msingi zilizowekwa kikatiba, zinazosimamiwa na mahakama huru, uhuru wa kisiasa na utawala wa sheria, zikizingatia ushiriki wa wanawake, vijana na watu wenye ulemavu.'],
      ['Utu', 'Kila mtu anastahili kuheshimiwa na kuthaminiwa utu wake, kulindwa na kuhakikishiwa faragha yake.'],
      ['Amani na umoja', 'Kila mtu anadumisha amani, umoja na mshikamano kama msingi wa maendeleo, akilinda Muungano wetu, watu wote wanaheshimiana na kuchangia malengo ya pamoja ya kitaifa.'],
      ['Utajiri na rasilimali asilia', 'Haki ya nchi kumiliki kikamilifu na kutumia utajiri na rasilimali zake kwa manufaa ya Taifa na ustawi wa wananchi wa sasa na vijavyo.'],
      ['Utamaduni na maadili ya taifa', 'Taifa linalohifadhi, kukuza na kulinda maadili na tamaduni chanya kwa lengo la kuimarisha umoja na utambulisho wa kitaifa kwa vizazi vya sasa na vijavyo.'],
    ],
    deliveryLabel: 'Itakavyotekelezwa',
    deliveryIntro: 'Dira 2050 inaeleza jinsi Dira itakavyotoka kwenye karatasi kwenda kwenye matokeo.',
    delivery: [
      ['Kuweka vipaumbele kimkakati', 'Kwa uchache wa rasilimali, Dira inaweka mkazo kwenye sekta chache za mageuzi, zilizochaguliwa kwa uwezo wake wa kuzalisha ajira, kuongeza mauzo ya nje, kuchochea sekta nyingine, kukuza pato na kuongeza thamani.'],
      ['Utekelezaji wa awamu', 'Utekelezaji unaongozwa na Mpango Elekezi wa Maendeleo wa Muda Mrefu wa miaka 25, unaotunga mipango ya miaka mitano (kuanzia FYDP IV) na mipango ya mwaka.'],
      ['Kushirikisha wadau wote', 'Mafanikio yanategemea ushirikiano: uongozi wa serikali, ubunifu wa sekta binafsi, asasi za kiraia na ushiriki wa wananchi, kupitia ubia wa sekta ya umma na binafsi.'],
      ['Uratibu na usimamizi', 'Tume ya Taifa ya Mipango, pamoja na Tume ya Mipango Zanzibar, inaratibu utekelezaji na kufungamanisha sera na mipango ya kisekta na malengo ya Dira.'],
      ['Ushahidi na uwajibikaji', 'Mfumo madhubuti wa kitaifa wa takwimu na ufuatiliaji unaotegemea ushahidi unaongoza maamuzi, ukisaidiwa na viashiria vya utendaji na motisha kwa uwajibikaji.'],
    ],
  },
  framework: {
    label: 'Muundo', title: 'Jinsi Dira 2050 ilivyojengwa.',
    intro: 'Msingi wa utawala bora unashikilia nguzo tatu. Vichocheo vitano vinazisukuma, vikitekeleza malengo ya Dira.',
    foundationLabel: 'Msingi',
    foundationIntro: 'Utawala bora, amani, usalama na utulivu: msingi ambao Dira nzima inaukalia.',
    pillarsLabel: 'Nguzo tatu', driversLabel: 'Vichocheo vitano',
  },
  pillar: {
    crumb: 'Nguzo', word: 'Nguzo', of: 'kati ya', aims: 'Inalenga nini · ifikapo 2050',
  },
  driver: {
    crumb: 'Vichocheo', word: 'Kichocheo', of: 'kati ya',
    targets: 'Shabaha · ifikapo 2050', aspirations: 'Matarajio',
    aspirationsIntro: 'Jinsi Tanzania inavyotaka kichocheo hiki kionekane ifikapo 2050.',
  },
  targets: {
    label: 'Shabaha',
    title: (n) => `Shabaha ${n}. Muda mmoja: 2050.`,
    intro: (m) => `Tanzania ilipo sasa, na Dira 2050 inakolenga. ${m} kati ya hizi zina takwimu ya 2050 inayopimika, na mistari inaonyesha ukubwa wa hatua inayohitajika. Kila takwimu inarejea ukurasa katika waraka wa chanzo.`,
    filters: { all: 'Zote', economy: 'Uchumi', people: 'Watu', environment: 'Mazingira', drivers: 'Vichocheo' },
    count: (n) => `Shabaha ${n}`,
    now: 'Sasa', goal: '2050', of: 'kati ya',
    tagEliminate: 'Kutokomeza', tagReduce: 'Kupunguza', tagIncrease: 'Kuongeza', tagGrow: 'Kukua',
  },
  timeline: {
    label: 'Ratiba', title: 'Kuanzia 2000 hadi 2050.',
    intro: 'Dira 2050 inajengwa juu ya miongo ya maendeleo na inaendeshwa kwa mpango wa miaka 25. Hizi ni alama muhimu: Tanzania ilipoanzia, ilipo sasa, na inakoelekea.',
  },
  forYou: {
    label: 'Kwako', title: 'Dira 2050 inamaanisha nini kwa maisha yako?',
    lead: 'Shabaha kubwa za kitaifa kwa kweli ni ahadi kuhusu mambo ya kila siku: kipato chako, umeme wako, maji yako, shule ya watoto wako. Haya ndiyo Dira inayolenga, kwa lugha rahisi. Gusa neno lolote lililopigiwa mstari kwa maelezo mafupi.',
    sections: [
      { h2: 'Pesa zaidi mfukoni mwako', parts: [
        'Mpango unalenga kuinua ', { label: 'wastani wa kipato cha mtu', def: 'Pato lote la nchi likigawanywa kwa idadi ya watu; kipimo cha jumla cha kipato cha mtu mmoja.' },
        ' hadi takriban dola 7,000 kwa mwaka, zaidi ya mara tano ya kiwango cha 2023. Unataka angalau nusu ya Watanzania wawe na ajira zenye staha katika sekta rasmi, na ',
        { label: 'umaskini uliokithiri', def: 'Kuishi kwa kipato kidogo mno kiasi cha kushindwa kumudu mahitaji ya msingi kama chakula na makazi.' }, ' utokomezwe kabisa.' ] },
      { h2: 'Umeme wa uhakika', parts: [
        'Leo mtu wa wastani anatumia takriban 170 ', { label: 'kWh', def: 'Kilowati-saa: kipimo cha umeme; matumizi makubwa kwa mtu mara nyingi yanaashiria uchumi ulioendelea zaidi.' },
        ' za umeme kwa mwaka. Ifikapo 2050 lengo ni angalau 3,000, ya kutosha kwa mwanga wa uhakika, vifaa na biashara ndogo, huku upotevu wa umeme ukishuka chini ya 10%.' ] },
      { h2: 'Maji safi na afya bora', parts: [
        'Dira inaahidi maji safi na salama kwa kila mtu, ', { label: 'huduma za afya kwa wote', def: 'Kila mtu anaweza kupata huduma za afya anazohitaji bila kuingia matatizo ya kifedha.' },
        ', na maisha marefu zaidi, wastani wa miaka 75. Inalenga kutokomeza vifo vya akina mama na watoto wakati wa kujifungua (leo ',
        { label: 'vifo vya uzazi', def: 'Idadi ya wanawake wanaofariki kutokana na ujauzito au kujifungua, kwa kila vizazi hai 100,000.' }, ' viko 104 kwa kila vizazi 100,000, kutoka 750 mwaka 2000).' ] },
      { h2: 'Shule na ujuzi kwa watoto wako', parts: [
        'Kila mtoto apate elimu bora kuanzia utotoni, kwa msukumo mkubwa kwenye ujuzi wa ',
        { label: 'STEM', def: 'Sayansi, Teknolojia, Uhandisi na Hisabati; ujuzi unaoonekana muhimu kwa uchumi wa kisasa.' },
        '. Angalau mtoto mmoja kati ya wanne afike elimu ya juu akiwa na ujuzi unaohitajika sokoni.' ] },
      { h2: 'Kuingia mtandaoni', parts: [
        'Mpango unataka angalau 70% ya wananchi wawe na ', { label: 'ujuzi wa kidijitali', def: 'Kuweza kutumia kompyuta, simu na intaneti kwa ujasiri katika shughuli za kila siku.' },
        ' na zaidi ya 80% ya huduma za serikali zipatikane mtandaoni, ili kulipa, kuomba na kujisajili kumaanishe foleni chache na safari chache.' ] },
      { h2: 'Nafasi sawa kwa kila mtu', parts: [
        'Ukuaji unakusudiwa kuwa jumuishi. Dira inawataja wanawake, vijana na watu wenye ulemavu, inalenga kupunguza pengo la kijinsia kwa angalau 85%, na inataka Tanzania ifikie ',
        { label: 'kipato cha kati ngazi ya juu', def: 'Kundi la kipato la Benki ya Dunia; Tanzania inalenga kupanda hadi humo kwa kuongeza kipato kwa mtu.' }, ' bila kumwacha mtu nyuma.' ] },
    ],
  },
  data: {
    label: 'Takwimu na vyanzo', title: 'Takwimu huru. Kila namba ina chanzo.',
    lead: 'Tovuti hii imejengwa kikamilifu kutoka waraka rasmi wa Dira 2050. Kila seti ya takwimu inapakuliwa kama faili la CSV, na kila namba ina ukurasa ilikotoka. Zitumie bila vikwazo.',
    downloadLabel: 'Pakua', methodologyLabel: 'Mbinu',
    methodologyBody: 'Namba zimetolewa kutoka waraka kamili wa kurasa 76. Pale waraka unapotoa msingi na lengo la 2050, vyote vinaonyeshwa. Visanduku tupu vinamaanisha waraka haukutoa thamani, si kubuni. Baadhi ya viashiria vya sekta na maelezo ya awamu bado yanahitaji kuchambuliwa zaidi; haya yameandikwa katika maelezo ya takwimu.',
    btnPdf: 'Waraka wa PDF', btnNotes: 'Maelezo ya takwimu', rows: 'safu',
    files: {
      'pillars.csv': 'Nguzo tatu', 'enablers.csv': 'Vichocheo vitano',
      'foundation.csv': 'Msingi wa utawala', 'targets.csv': 'Shabaha za taifa, nguzo, vichocheo na sekta',
      'sectors.csv': 'Sekta za mageuzi', 'sector_kpis.csv': 'Takwimu za msingi za sekta',
      'sector_criteria.csv': 'Vigezo vya kuchagua sekta', 'aspirations.csv': 'Matarajio ya vichocheo',
      'milestones.csv': 'Alama za ratiba', 'glossary.csv': 'Maelezo ya lugha rahisi',
      'sources.csv': 'Ramani ya sehemu za waraka',
    },
  },
  about: {
    label: 'Kuhusu', title: 'Dira 2050, kwa uwazi.',
    lead: 'Mwongozo wa lugha rahisi kwa mwananchi kuhusu Dira ya Taifa ya Maendeleo 2050, ili kila Mtanzania aelewe nchi inakoelekea.',
    noteLabel: 'Tafadhali fahamu',
    noteBody: 'Haya ni malengo, si mafanikio. Kila shabaha katika tovuti hii ni lengo la kitaifa la mwaka 2050 kama lilivyowekwa katika waraka wa Dira. Yanaeleza Tanzania inayolenga, si yaliyokwisha fikiwa. Pale shabaha ina mahali pa kuanzia, tunaonyesha takwimu ya leo pembeni na lengo la 2050 ili umbali uwe wazi.',
    sourceLabel: 'Chanzo',
    sourceBody: 'Jamhuri ya Muungano wa Tanzania. (2025). Dira ya Taifa ya Maendeleo 2050 (Dira 2050). Dodoma: Tume ya Mipango. Maudhui yote ya tovuti hii yametokana na waraka huo.',
    independentLabel: 'Huru',
    independentBody: 'Huu ni mwongozo huru wa kusaidia uelewa wa umma. Si chapisho rasmi la serikali.',
    founderLabel: 'Kuhusu mwanzilishi',
    founderP1: 'Mradi huu ni sehemu ya jitihada pana za kuanzisha Taasisi huru ya Uonyeshaji wa Taarifa (Information Visualization Institute), inayolenga kurahisisha uelewa wa taarifa tata za umma kupitia mawasiliano ya kuona yaliyo wazi, yanayofikika na yenye msingi wa ushahidi. Dira ya muda mrefu ni kugeuza mikakati ya serikali, sera, tafiti, takwimu, bajeti na ripoti za maendeleo kuwa uzoefu shirikishi unaosaidia wananchi, watafiti, watunga sera, waelimishaji na washirika wa maendeleo kuelewa masuala yanayounda jamii.',
    founderP2: 'Jitihada hii ilianzishwa na Gerald Tesha, Mhandisi wa Mifumo ya Taarifa na Mitandao (St. Joseph College of Engineering and Technology) mwenye utaalamu wa Uonyeshaji wa Taarifa kutoka NYU Tandon School of Engineering. Akiwa Dodoma, Tanzania, Gerald ana uzoefu wa zaidi ya miaka tisa katika takwimu, ufuatiliaji na tathmini, usimamizi wa taarifa na uonyeshaji katika programu za afya na maendeleo ya kimataifa Kusini mwa Jangwa la Sahara.',
    founderP3: 'Washirika, watafiti, wabunifu, wahandisi wa programu, taasisi na mashirika wanaopenda kuendeleza kazi hii wanakaribishwa kuwasiliana.',
  },
  si: {
    deepDive: 'Uchambuzi wa kina', eyebrow: 'Fursa na Ujasusi wa Kimkakati',
    h2: 'Usisome tu mpango. Tafuta nafasi yako ndani yake.',
    lead: 'Kila mkakati wa kitaifa unaashiria kimya kimya uwekezaji, ajira, ujuzi na ukuaji unakoelekea. Safu hii inatoa ujasusi huo kutoka Dira 2050 na kuugeuza kuwa maamuzi unayoweza kuyachukua.',
    legendDoc: 'imeelezwa katika waraka.', legendInf: 'uchambuzi wetu wa maana yake.',
    forLabel: 'Ujasusi kwa…',
    opportunities: 'Fursa', actions: 'Hatua za kuzingatia', skills: 'Ujuzi wa kujenga',
    sectors: 'Sekta za kufuatilia', engage: 'Taasisi za kushirikiana nazo',
    tailored: (a) => `uchambuzi maalum kwa ${a}.`,
    outlookLabel: 'Mtazamo wa sekta',
    outlookIntro: 'Pale waraka unapoelekeza uangalifu mkubwa. Mistari inaonyesha msisitizo wa kimkakati (1–5), uliosomwa kutoka shabaha, vichocheo na sekta zilizotajwa.',
    mapLabel: 'Ramani ya fursa',
    skillsLabel: 'Ujuzi unaohitajika',
    skillsIntro: 'Ujuzi ambao mpango utautegemea: cha kusoma, kufundisha au kujifunza upya.',
    demand: (d) => `mahitaji ${d}`,
    briefingLabel: 'Muhtasari wa kimkakati',
    briefingIntro: 'Picha ya jumla: mpango unapaweka kipaumbele, unategemea nini, uko dhaifu wapi, na nyenzo zenye uwezekano mkubwa wa kuusukuma.',
    oppIntro: 'Yale Dira inayofungua, kulingana na wewe ni nani: fursa, hatua za kuzingatia, ujuzi wa kujenga, sekta za kufuatilia na taasisi za kushirikiana nazo.',
    mapIntro: 'Fursa halisi Dira inazounda, zinazoweza kuchujwa kwa aina. Kila moja imehusishwa na waraka.',
    back: 'Rudi Kwako',
    exploreLabel: 'Chunguza uchambuzi',
    explore: [
      ['opportunities', 'Fursa', 'Yale Dira inayofungua kwako, kulingana na wewe ni nani.'],
      ['sector-outlook', 'Mtazamo wa sekta', 'Pale mpango unapoelekeza uangalifu mkubwa, sekta kwa sekta.'],
      ['opportunity-map', 'Ramani ya fursa', 'Fursa halisi, zinazoweza kuchujwa kwa aina, kila moja ikihusishwa na waraka.'],
      ['skills', 'Ujuzi unaohitajika', 'Ujuzi ambao mpango utautegemea.'],
      ['briefing', 'Muhtasari wa kimkakati', 'Vipaumbele, utegemezi, udhaifu na nyenzo zinazousukuma.'],
    ],
  },
  notFound: { code: '404', title: 'Ukurasa haukupatikana.', body: 'Ukurasa unaoutafuta haupo.', home: 'Rudi mwanzo' },
  pro: {
    nav: 'PRO',
    home: {
      eyebrow: 'Ujasusi wa Taarifa za Kitaifa',
      title: 'Dira 2050, kama jukwaa hai la ujasusi.',
      lead: 'Zaidi ya waraka: uchunguzi shirikishi wenye msingi wa ushahidi wa yale Tanzania inayolenga kufikia, kwa nini yanajalisha, na jinsi unavyoweza kushiriki.',
      cta: 'Ingia kwenye Simulizi Kuu', ctaExplore: 'Vinjari Dira',
      keyNumbers: 'Lengo la 2050, katika namba tatu',
      roadmapLabel: 'PRO inafungua nini', roadmapLead: 'Mkusanyiko wa moduli za ujasusi, zinazojengwa kwa awamu juu ya msingi huu.',
      libraryLabel: 'Imejengwa kwa zana za usimulizi', libraryLead: 'Vipengele vinavyoweza kutumika tena, vya lugha mbili na vinavyofikika, vinavyoendesha kila simulizi la PRO.',
      comingSoon: 'Inakuja hivi karibuni',
    },
    story: {
      scrollCue: 'Sogeza kuanza',
      journeyEyebrow: 'Safari',
      journeyTitle: 'Miongo sita ya maendeleo, mpango mmoja wa miaka 25.',
      journeyLead: 'Dira 2050 inajengwa juu ya Tanzania ilipotoka na inaweka mwelekeo wazi wa inakoelekea.',
      transformEyebrow: 'Mageuzi',
      transformTitle: 'Ukubwa halisi wa hatua.',
      transformLead: 'Si kauli mbiu, bali mabadiliko yanayopimika kutoka leo hadi 2050.',
      leapGrowth: 'ukuaji ifikapo 2050',
      leapCut: 'upunguzaji ifikapo 2050',
      numbersEyebrow: 'Lengo, kwa namba',
      pillarsEyebrow: 'Muundo',
      pillarsTitle: 'Nguzo tatu, msingi mmoja.',
      pillarsLead: 'Kila kitu kinasimama juu ya utawala bora, na kinainuka kupitia uchumi imara, watu wenye uwezo na mazingira yenye afya.',
      ambitionsEyebrow: 'Malengo ya kitaifa',
      ambitionsTitle: 'Mafanikio yanavyoonekana ifikapo 2050.',
      ctaEyebrow: 'Nenda ndani zaidi',
      ctaTitle: 'Huu ni mwanzo tu.',
      ctaLead: 'Vinjari Dira kwa kina, au ingia kwenye moduli za ujasusi zinapofunguliwa.',
      ctaVision: 'Vinjari muundo', ctaTargets: 'Ona kila shabaha', ctaForYou: 'Inamaanisha nini kwako',
    },
    subnav: { story: 'Simulizi', explore: 'Vinjari', graph: 'Ramani', opps: 'Fursa', skills: 'Ujuzi', audiences: 'Hadhira', regions: 'Kanda', sectors: 'Sekta', charts: 'Chati', evidence: 'Ushahidi', ask: 'Uliza', progress: 'Maendeleo' },
    progress: {
      title: 'Ufuatiliaji wa Maendeleo',
      lead: 'Muundo wa kufuatilia utekelezaji dhidi ya kila shabaha ya 2050. Viashiria vya moja kwa moja vitaunganishwa hapa data rasmi ikipatikana.',
      note: 'Ufuatiliaji wa moja kwa moja bado haujaunganishwa. Mtazamo huu umejengwa kupokea data rasmi ya viashiria kupitia adapta ya kawaida, hakuna kubuni upya itakapofika.',
      baseline: 'Msingi', goal: 'Lengo la 2050', current: 'Sasa', awaiting: 'Inasubiri data',
      statusNodata: 'Ufuatiliaji unasubiri', statusOn: 'Kwenye mstari', statusBehind: 'Nyuma', statusMet: 'Imefikiwa',
    },
    error: {
      badge: 'Hitilafu imetokea',
      title: 'Mtazamo huu haukuweza kuonyeshwa',
      body: 'Hitilafu isiyotarajiwa ilizuia sehemu hii kupakia. Sehemu nyingine za jukwaa hazijaathirika. Unaweza kujaribu tena, au kurudi kwenye muhtasari.',
      retry: 'Jaribu tena', home: 'Rudi kwenye muhtasari',
    },
    ask: {
      title: 'Uliza Dira',
      lead: 'Msaidizi binafsi anayejibu kutoka Dira, kikamilifu ndani ya kivinjari chako. Hakuna data inayoondoka kifaani.',
      placeholder: 'Uliza swali kuhusu Dira 2050…', ask: 'Uliza',
      suggestions: ['Shabaha za 2050 za nishati ni zipi?', 'Fursa katika utalii', 'Ujuzi upi wanafunzi wajenge?', 'Kielelezo cha Mtaji Watu ni nini?', 'Eleza nguzo ya uchumi'],
      answerLead: 'Haya ndiyo Dira 2050 inasema, kutoka takwimu:',
      noAnswer: 'Sikupata kitu kuhusu hilo katika Dira. Jaribu maneno tofauti, au vinjari sehemu.',
      privacy: 'Inaendeshwa kikamilifu ndani ya kivinjari · hakuna miito ya nje',
      types: { pillar: 'Nguzo', driver: 'Kichocheo', sector: 'Sekta', target: 'Shabaha', foundation: 'Msingi', glossary: 'Maana', opportunity: 'Fursa', skill: 'Ujuzi', audience: 'Hadhira', region: 'Kanda', strategic: 'Uchambuzi' },
    },
    evidence: {
      title: 'Ushahidi na Mbinu',
      lead: 'Kila namba na dai kwenye jukwaa hili linarejea chanzo. Hivi ndivyo, na wapi.',
      methodTitle: 'Imeandikwa dhidi ya Uchambuzi',
      methodBody: 'Ukweli ulioelezwa katika waraka wa Dira umewekwa "Imeandikwa". Hitimisho za uchambuzi tunazopata (fursa, ujuzi, mtazamo wa kanda na sekta) zimewekwa "Uchambuzi", ili ujue kila wakati kipi ni kipi.',
      statDatasets: 'Seti za takwimu', statFigures: 'Shabaha zinazofuatiliwa', statSections: 'Sehemu za waraka',
      sourcesTitle: 'Sehemu za waraka', sourcesLead: 'Dira ya Taifa ya Maendeleo 2050, iliyoainishwa kwa sehemu na ukurasa.',
      colSection: 'Sehemu', colPages: 'Kurasa',
      pdf: 'Waraka wa PDF', downloads: 'Pakua takwimu',
    },
    charts: {
      title: 'Simulizi za Takwimu', lead: 'Chati zinazojibu swali, si kupamba ukurasa.',
      treemapTitle: 'Nini kinaunda uchumi leo?', treemapNote: 'Kwa sehemu ya pato la taifa. “Nyingine na huduma” ni sehemu iliyobaki.',
      sankeyTitle: 'Vichocheo vipi vinasukuma sekta zipi?', sankeyNote: 'Viungo vya uwezeshaji kutoka vichocheo vitano hadi sekta za mageuzi.',
      smTitle: 'Hatua ya kila shabaha, kwa mtazamo mmoja', smNote: 'Leo (kijivu) dhidi ya lengo la 2050 (kijani), kila moja kwa kiwango chake.',
      other: 'Nyingine na huduma', now: 'Sasa', goal: '2050',
    },
    sector: {
      title: 'Ujasusi wa Sekta',
      lead: 'Lango kwa kila sekta ya mageuzi: ilipo leo, inakoelekea ifikapo 2050, na fursa zilizomo.',
      badge: 'Sekta', ambition: 'Lengo la 2050', kpis: 'Takwimu muhimu', opportunities: 'Fursa', connections: 'Sekta nyingine',
      why: 'Kwa nini yanajalisha', take: 'Kitakachohitajika', momentum: 'Kasi', pageAbbr: 'uk.',
    },
    regions: {
      title: 'Ujasusi wa Kikanda',
      lead: 'Jinsi Dira inavyotekelezwa nchini kote: vipaumbele, viwanda, rasilimali na fursa za kila kanda.',
      disclaimer: 'Maelezo ya kanda ni muhtasari wa uchambuzi na kielelezo. Dira inaweka mwelekeo wa kitaifa, si maelezo ya kanda kwa kanda.',
      selectLabel: 'Chagua kanda', mapNote: 'Ramani ya mchoro, si kwa kipimo',
      priorities: 'Vipaumbele vya maendeleo', industries: 'Viwanda', resources: 'Rasilimali', opportunities: 'Fursa',
    },
    audience: {
      title: 'Ujasusi wa Hadhira',
      lead: 'Mwongozo maalum kulingana na wewe ni nani: fursa, hatua, ujuzi na taasisi zinazokujali zaidi.',
      choose: 'Chagua nafasi yako', backAll: 'Hadhira zote', ctaSkills: 'Vinjari ujuzi', ctaOpps: 'Vinjari fursa',
    },
    skills: {
      title: 'Ujasusi wa Ujuzi',
      lead: 'Uwezo ambao Dira itautegemea: cha kusoma, kufundisha au kujifunza upya, pamoja na njia za kujifunza na mustakabali wa kazi.',
      allCats: 'Maeneo yote', allDemand: 'Mahitaji yote',
      whereLabel: 'Katika mkakati', learningLabel: 'Njia ya kujifunza', certsLabel: 'Vyeti',
      programsLabel: 'Programu za chuo', outlookLabel: 'Mustakabali wa kazi', demandLabel: 'Mahitaji',
      count: (n) => `ujuzi ${n}`,
      cats: { Digital: 'Kidijitali', Policy: 'Sera', Engineering: 'Uhandisi', Agriculture: 'Kilimo', Operations: 'Uendeshaji', Environment: 'Mazingira', Research: 'Utafiti', Health: 'Afya' },
    },
    opps: {
      title: 'Ujasusi wa Fursa',
      lead: 'Yale Dira inayofungua: fursa za biashara, uwekezaji, ajira na ubunifu zilizopangwa, kila moja ikihusishwa na waraka.',
      allTypes: 'Aina zote', allTimes: 'Nyakati zote',
      stakeholders: 'Nani', impact: 'Athari inayowezekana', evidence: 'Ushahidi', priority: 'Kipaumbele',
      timelines: { 'Near-term': 'Muda mfupi', 'Medium-term': 'Muda wa kati', 'Long-term': 'Muda mrefu' },
      count: (n) => `fursa ${n}`,
    },
    graph: {
      title: 'Ramani ya Maarifa',
      lead: 'Jinsi Dira inavyounganika: kutoka lengo, kupitia nguzo na vichocheo, hadi sekta zinazoitekeleza. Bofya nodi yoyote kuvinjari.',
      visionNode: 'Dira 2050',
      legend: { vision: 'Dira', pillar: 'Nguzo', driver: 'Vichocheo', sector: 'Sekta' },
      listLabel: 'Nodi zote',
      structureTitle: 'Muundo',
      structureLead: 'Dira ikisomwa kutoka juu hadi chini: lengo, nguzo tatu, vichocheo vinavyoziwezesha, na sekta ambako yanatekelezwa.',
      connectionsTitle: 'Muunganiko',
      connectionsLead: 'Dira ile ile kama mtandao. Elea au gusa nodi yoyote kufuatilia jinsi nguzo, vichocheo na sekta zinavyounganika.',
      tiers: { vision: 'Dira', pillars: 'Nguzo · malengo', drivers: 'Vichocheo · viwezeshaji', sectors: 'Sekta · zinakotekelezwa' },
    },
    storyt: {
      why: 'Kwa nini yanajalisha', aims: 'Inalenga nini ifikapo 2050', aspirations: 'Matarajio',
      timeline: 'Safari hadi 2050', connections: 'Vinjari zaidi', fullPage: 'Ona ukurasa kamili',
    },
    stories: {
      why: {
        economy: 'Uchumi mkubwa na wa haki ndio unaogharimia kila kitu kingine: shule, hospitali, barabara na ajira. Bila ukuaji unaowafikia wote, malengo mengine yanabaki mbali.',
        people: 'Watu ndio lengo la maendeleo. Wananchi wenye afya, elimu na usalama zaidi ni lengo la Dira na pia nguvu kazi inayoitekeleza.',
        environment: 'Ardhi, maji na wanyamapori wa Tanzania ni utajiri wa taifa na riziki ya mamilioni. Kuvilinda, na kukabiliana na mabadiliko ya tabianchi, kunazuia ukuaji usijidhoofishe.',
        logistics: 'Usafirishaji wa polepole na ghali hufanya kila kitu kuwa ghali zaidi. Usafirishaji nafuu na wa kasi hufungua biashara, viwanda na uongozi wa kikanda.',
        energy: 'Karibu hakuna kitu katika Dira kinachofanya kazi bila umeme. Nishati ya uhakika na nafuu ni sharti la viwanda, huduma za kidijitali na maisha ya kisasa.',
        'science-tech': 'Teknolojia ndiyo njia ya uchumi mdogo kuruka hatua. Sayansi tumizi huongeza kile mkulima, kliniki au kiwanda kinachoweza kuzalisha.',
        rnd: 'Utafiti hugeuza matatizo kuwa bidhaa na ushahidi kuwa sera. Ingawa haujapewa fedha za kutosha leo, ndio injini ya ushindani wa muda mrefu.',
        digital: 'Kwenda kidijitali hupunguza gharama na umbali: foleni chache, masoko mapana, na huduma zinazofika vijijini. Kinapita katika kila lengo lingine.',
      },
    },
    explore: {
      title: 'Vinjari Dira',
      lead: 'Tafuta na uvinjari kila sehemu ya Dira 2050: malengo, shabaha, nguzo, vichocheo, sekta na zaidi, vyote vikiunganishwa.',
      searchPlaceholder: 'Tafuta Dira…',
      related: 'Imeunganishwa na', open: 'Fungua',
      noResults: 'Hakuna kinacholingana na utafutaji wako.',
      count: (n) => `matokeo ${n}`,
      facet: { all: 'Zote', goal: 'Malengo', target: 'Shabaha', pillar: 'Nguzo', driver: 'Vichocheo', sector: 'Sekta', foundation: 'Msingi', principle: 'Kanuni', theme: 'Mada' },
      badge: { goal: 'Lengo', target: 'Shabaha', pillar: 'Nguzo', driver: 'Kichocheo', sector: 'Sekta', foundation: 'Msingi', principle: 'Kanuni', theme: 'Mada' },
      principles: [
        ['Maendeleo yanayomlenga mtu', 'Ukuaji unaoboresha maisha ya kila mwananchi, bila kumwacha mtu nyuma.'],
        ['Mamlaka juu ya rasilimali', 'Kutumia utajiri wa asili wa taifa kwa manufaa ya kizazi cha sasa na kijacho.'],
        ['Utamaduni na maadili ya taifa', 'Kuhifadhi urithi, utambulisho na umoja kama msingi wa maendeleo.'],
        ['Utawala bora', 'Ukatiba, utawala wa sheria na uwajibikaji kama msingi wa Dira.'],
      ],
      themes: [
        ['Ujumuishaji', 'Wanawake, vijana na watu wenye ulemavu ni kiini cha kila lengo.'],
        ['Vijana na idadi ya watu', 'Idadi changa ya watu kama injini ya mageuzi.'],
        ['Mageuzi ya kidijitali', 'Teknolojia iliyofumwa katika uchumi na huduma za umma.'],
        ['Ustahimilivu wa tabianchi', 'Kukabiliana na mabadiliko ya tabianchi katika kila sekta.'],
        ['Ajira na ujuzi', 'Kazi zenye staha, na uwezo wa kuzijaza.'],
      ],
    },
    modules: [
      ['Simulizi Kuu', 'Utangulizi wa Dira wa kusisimua unaoendeshwa kwa kusogeza.'],
      ['Kivinjari cha Dira', 'Vinjari kwa malengo, shabaha, nguzo, vichocheo na sekta, vyote vikiunganishwa.'],
      ['Ramani ya Maarifa', 'Ona jinsi malengo, sekta, ujuzi, mikoa na taasisi vinavyounganika.'],
      ['Ujasusi wa Fursa', 'Fursa za biashara, uwekezaji na ubunifu zilizopangwa kwa kila sehemu.'],
      ['Ujasusi wa Ujuzi', 'Ujuzi wa baadaye, njia za kujifunza na mustakabali wa kazi.'],
      ['Uliza Dira', 'Msaidizi binafsi anayejibu maswali kutoka waraka.'],
    ],
    demo: {
      quote: 'Ifikapo 2050, tutajenga nchi ya kipato cha kati ngazi ya juu yenye watu zaidi ya milioni 118, ikiwa na uchumi wa dola trilioni moja.',
      quoteCite: 'Dira ya Taifa ya Maendeleo 2050',
      compareLabel: 'Kipato kwa mtu (dola)',
      calloutTitle: 'Kila kitu hapa kina msingi wa ushahidi',
      calloutBody: 'Kila namba na dai linarejea waraka wa Dira, na hitimisho za uchambuzi zimewekwa wazi tofauti na ukweli ulioandikwa.',
      expTitle: 'Dira imepangwaje?',
      expBody: 'Msingi wa utawala bora unashikilia nguzo tatu (uchumi, watu, mazingira). Vichocheo vitano vinazisukuma, vikitekelezwa kupitia sekta za mageuzi zilizopewa kipaumbele.',
      tl: [
        ['2000', 'Mahali pa kuanzia', 'Kipato kwa mtu dola 453; umaskini uliokithiri 36%.'],
        ['2025', 'Dira 2050 yazinduliwa', 'Mwelekeo wa taifa wa miaka 25 unawekwa.'],
        ['2050', 'Tanzania tunayoitaka', 'Uchumi wa dola trilioni moja, kipato cha kati ngazi ya juu.'],
      ],
    },
  },
  maps: {
    demand: { High: 'makubwa', Medium: 'ya wastani' },
    signal: { Rising: 'Inapanda', Emerging: 'Inachipuka' },
    category: { Priority: 'Kipaumbele', Dependency: 'Utegemezi', 'Capability gap': 'Pengo la uwezo', Bottleneck: 'Kizuizi', 'Leverage point': 'Nyenzo ya kusukuma', Risk: 'Hatari' },
    categoryPlural: { Priority: 'Vipaumbele', Dependency: 'Tegemezi', 'Capability gap': 'Mapengo ya uwezo', Bottleneck: 'Vizuizi', 'Leverage point': 'Nyenzo za kusukuma', Risk: 'Hatari' },
    oppType: { Investment: 'Uwekezaji', 'Local manufacturing': 'Uzalishaji wa ndani', Export: 'Mauzo ya nje', Startup: 'Biashara mpya', Innovation: 'Ubunifu', Research: 'Utafiti', PPP: 'Ubia (PPP)', Employment: 'Ajira', 'Capacity-building': 'Kujenga uwezo', 'Technology adoption': 'Matumizi ya teknolojia', Funding: 'Ufadhili' },
  },
}

export default { en, sw }
